const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const role=fs.readFileSync('supabase/migrations/202608100004_bar_lead_role.sql','utf8'),sql=fs.readFileSync('supabase/migrations/202608100005_bar_lead_access.sql','utf8'),gate=fs.readFileSync('auth-gate.js','utf8'),css=fs.readFileSync('auth.css','utf8');

test('Bar Lead enum migration is isolated before policies reference it',()=>{assert.match(role,/alter type public\.app_role add value if not exists 'bar_lead'/);assert.doesNotMatch(role,/^\s*(?:begin|commit)\s*;/im);assert.match(sql,/public\.app_role/)});
test('Bar Lead RLS grants operational orders and receiving but withholds privileged work',()=>{for(const policy of ['order_insert','order_update','order_line_insert','order_line_update','session_insert','session_update','receiving_line_insert','receiving_line_update'])assert.match(sql,new RegExp(`create policy ${policy}[\\s\\S]{0,700}bar_lead`));for(const forbidden of ['baseline_insert','baseline_line_insert','reconciliation_request','exception_approve'])assert.doesNotMatch(sql,new RegExp(`create policy ${forbidden}[\\s\\S]{0,500}bar_lead`))});
test('invitation lifecycle is tenant scoped, expiring, revocable, resendable, and idempotent',()=>{assert.match(sql,/one_pending_invitation_per_location_email/);assert.match(sql,/organization_id,location_id,email\) where status='pending'/);assert.match(sql,/expires_at<=now\(\) then 'expired'/);assert.match(sql,/resend_count=resend_count\+1/);assert.match(sql,/status='revoked'/);assert.match(sql,/on conflict\(organization_id,user_id\) do nothing/);assert.match(sql,/on conflict do nothing/)});
test('invitation acceptance supports existing and new users without trusting UI state',()=>{assert.match(sql,/from auth\.users where lower\(email\)=normalized/);assert.match(sql,/insert into public\.profiles[\s\S]*on conflict\(id\) do nothing/);assert.match(sql,/auth\.jwt\(\)->>'email'/);assert.match(sql,/sent_at<=issued_at/);assert.match(sql,/security definer set search_path=pg_catalog,public,pg_temp/);assert.match(sql,/revoke all on function[\s\S]*from public,anon/)});
test('administrator actions are database-authorized and non-admin direct UI calls fail closed',()=>{for(const fn of ['admin_create_invitation','admin_list_invitations','admin_resend_invitation','admin_revoke_invitation','admin_change_member_role'])assert.match(sql,new RegExp(`create function public\\.${fn}[\\s\\S]{0,700}Administrator access required`));assert.match(gate,/if\(!window\.POURGRID_AUTH_CONTEXT\?\.capabilities\?\.admin/);assert.match(gate,/if\(canManageTeam\(context\)\)installAdminAccess/);assert.match(gate,/\['administrator','manager'\]\.includes\(context\?\.role\)/)});
test('sign-out removes administrator access capability and invitation UI',()=>{assert.match(gate,/window\.POURGRID_ADMIN_API=null/);assert.match(gate,/getElementById\('pgTeamAccess'\)\?\.remove/);assert.match(gate,/getElementById\('pgTeamModal'\)\?\.remove/);assert.match(gate,/clearSessionState\(localStorage\)/)});
test('secure invitation email uses a non-persistent secondary Supabase client',()=>{assert.match(gate,/inviteClient=createClient/);assert.match(gate,/persistSession:false,autoRefreshToken:false,detectSessionInUrl:false/);assert.match(gate,/inviteClient\.auth\.signInWithOtp/);assert.doesNotMatch(gate,/service_role/)});
test('administrator dialog is accessible and mobile-safe at 320px and 390px',()=>{for(const token of ['role="dialog"','aria-modal="true"','aria-labelledby="pgTeamTitle"','aria-haspopup','aria-live="polite"','aria-label="Close team access"'])assert.ok(gate.includes(token),token);assert.match(css,/@media\(max-width:390px\)/);assert.match(css,/min-height:44px/);assert.match(css,/width:min\(100%,560px\)/);assert.match(css,/overflow-wrap:anywhere/)});
