const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8');
const gate=read('auth-gate.js'),fn=read('netlify/functions/onboard-employee.mjs'),migration=read('supabase/migrations/202608110008_manager_temporary_onboarding.sql');

test('manager onboarding uses a server-only Supabase admin client',()=>{assert.match(fn,/process\.env\.SUPABASE_SERVICE_ROLE_KEY/);assert.match(fn,/admin\.auth\.admin\.createUser/);assert.match(fn,/admin\.auth\.admin\.updateUserById/);assert.match(fn,/email_confirm:true/);assert.doesNotMatch(gate,/SUPABASE_SERVICE_ROLE_KEY|service_role/)});
test('every issuance generates an independent strong one-time password',()=>{assert.match(fn,/randomBytes\(24\)/);assert.match(fn,/const password=temporaryPassword\(\)/);assert.doesNotMatch(fn,/S@pph1re|password123|temporaryPassword\s*:\s*['"]/i);assert.match(migration,/admin_issue_temporary_password\(p_email\)/)});
test('manager authorization is checked before any auth user mutation',()=>{const allow=fn.indexOf("service_manager_can_onboard"),lookup=fn.indexOf('const existing=await findUserByEmail'),update=fn.indexOf('updateUserById'),create=fn.indexOf('createUser');assert.ok(allow>=0&&allow<lookup&&lookup<update&&lookup<create);assert.match(migration,/m\.role in \('administrator','manager'\)/);assert.match(migration,/grant execute[\s\S]*to service_role/);assert.doesNotMatch(migration,/grant execute[\s\S]*to authenticated/)});
test('existing users are reused and future-user failure is compensated',()=>{assert.match(fn,/if\(existing\)/);assert.match(fn,/existing\.id/);assert.match(fn,/existingUser:true/);assert.match(fn,/deleteUser\(created\.data\.user\.id\)/);assert.doesNotMatch(fn,/createUser\([\s\S]*if\(existing\)/)});
test('database onboarding preserves identity and upserts scoped membership',()=>{assert.match(migration,/where id=p_user and lower\(email\)=normalized for update/);assert.match(migration,/on conflict\(organization_id,user_id\) do update set role=excluded\.role/);assert.match(migration,/on conflict\(membership_id,location_id\)/);assert.match(migration,/password_change_requirements/);assert.match(migration,/delete from auth\.sessions where user_id=p_user/);assert.match(migration,/employee\.temporary_access_issued/)});
test('manager UI reveals the credential only in memory and never stores or logs it',()=>{assert.match(gate,/Create one-time access/);assert.match(gate,/result\.temporaryPassword/);assert.match(gate,/navigator\.clipboard\.writeText\(result\.temporaryPassword\)/);assert.doesNotMatch(gate,/localStorage\.setItem\([^\n]*temporaryPassword|console\.(?:log|error)\([^\n]*temporaryPassword/);assert.match(fn,/cache-control':'no-store/)});
test('employees remain gated until permanent password replacement',()=>{assert.match(gate,/requirePermanentPassword/);assert.match(gate,/complete_required_password_change/);assert.match(migration,/required=true,temporary_password_hash=excluded\.temporary_password_hash/);assert.match(read('supabase/migrations/202608110006_required_password_change.sql'),/current_hash=temporary_hash/)});
