const test=require('node:test');const assert=require('node:assert/strict');const P=require('../phase3-domain');
const scope={organizationId:'sbb',locationId:'main',workflow:'bar'};
function order(workflow='bar'){return {id:'o1',...scope,workflow,status:'submitted',lines:[{id:'l1',itemId:'vodka',expectedUnits:24,receivedUnits:0}]};}
test('role boundaries deny anonymous/viewer and reserve approval for managers',()=>{assert.equal(P.can(null,'view'),false);assert.equal(P.can('read_only_viewer','mutate'),false);assert.equal(P.can('inventory_staff','mutate'),true);assert.equal(P.can('inventory_staff','approve'),false);assert.equal(P.can('manager','approve'),true);assert.equal(P.can('administrator','admin'),true)});
test('package-to-unit conversion is exact and rejects unsafe values',()=>{assert.equal(P.units(2,3,12),27);assert.throws(()=>P.units(1.5,0,12));assert.throws(()=>P.units(-1,0,12))});
test('baseline requires manager and is immutable through replacement',()=>{let s=P.createState();assert.throws(()=>P.finalizeBaseline(s,{vodka:10},'staff','inventory_staff',scope));P.finalizeBaseline(s,{vodka:10},'mgr','manager',scope);assert.equal(P.reconstruct(s,'main','vodka'),10);assert.throws(()=>P.finalizeBaseline(s,{vodka:9},'mgr','manager',scope))});
test('partial and multiple receipts preserve remaining quantities',()=>{let s=P.createState(),o=order();P.finalizeBaseline(s,{vodka:0},'mgr','manager',scope);let a=P.startSession(s,o,'staff','inventory_staff');P.recordLine(s,a,'l1',{packages:1,loose:0,unitsPerPackage:12},'staff','inventory_staff');P.finalizeReceipt(s,a.id,o,'staff','inventory_staff');assert.equal(o.status,'partially_received');assert.equal(P.remaining(o.lines[0]),12);let b=P.startSession(s,o,'staff','inventory_staff');P.recordLine(s,b,'l1',{packages:0,loose:12,unitsPerPackage:12},'staff','inventory_staff');P.finalizeReceipt(s,b.id,o,'staff','inventory_staff');assert.equal(o.status,'received');assert.equal(P.reconstruct(s,'main','vodka'),24)});
test('receipt finalization is idempotent and never duplicates movement',()=>{let s=P.createState(),o=order();P.finalizeBaseline(s,{vodka:0},'mgr','manager',scope);let x=P.startSession(s,o,'staff','inventory_staff');P.recordLine(s,x,'l1',{packages:1,loose:0,unitsPerPackage:12},'staff','inventory_staff');P.finalizeReceipt(s,x.id,o,'staff','inventory_staff');P.finalizeReceipt(s,x.id,o,'staff','inventory_staff');assert.equal(s.movements.filter(m=>m.kind==='receipt').length,1)});
test('substitutions and over receipts cannot finalize without approval',()=>{let s=P.createState(),o=order();P.finalizeBaseline(s,{vodka:0},'mgr','manager',scope);let x=P.startSession(s,o,'staff','inventory_staff');let l=P.recordLine(s,x,'l1',{packages:3,loose:0,unitsPerPackage:12,substitutionItemId:'gin',reason:'vendor replacement'},'staff','inventory_staff');assert.throws(()=>P.finalizeReceipt(s,x.id,o,'staff','inventory_staff'));P.decideException(s,l.exceptionId,true,'mgr','manager');P.finalizeReceipt(s,x.id,o,'staff','inventory_staff');assert.equal(P.reconstruct(s,'main','gin'),36)});
test('reconciliation uses a manager-approved compensating movement',()=>{let s=P.createState();P.finalizeBaseline(s,{vodka:10},'mgr','manager',scope);let r=P.requestReconciliation(s,scope,'vodka',-2,'breakage','staff','inventory_staff');assert.throws(()=>P.approveReconciliation(s,r.id,true,'staff','inventory_staff'));P.approveReconciliation(s,r.id,true,'mgr','manager');assert.equal(P.reconstruct(s,'main','vodka'),8);assert.equal(s.movements.at(-1).kind,'reconciliation')});
test('Bar and Merchants movements remain isolated',()=>{let s=P.createState();P.finalizeBaseline(s,{vodka:0,juice:0},'mgr','manager',{...scope,workflowByItem:{vodka:'bar',juice:'merchants'}});assert.equal(s.movements.find(m=>m.itemId==='vodka').workflow,'bar');assert.equal(s.movements.find(m=>m.itemId==='juice').workflow,'merchants')});
