const test=require('node:test');
const assert=require('node:assert/strict');
const Vision=require('../pourgrid-vision.js');
const BI=require('../bottle-intelligence.js');

const products=[
  {id:'pine',name:'Pineapple Juice',dist:'Merchants',cat:'Mixer',unit:'Case',pack:8,buildTo:72,visionPackaging:{mode:'caseLoose',unitsPerCase:8,unitLabel:'bottles',buildToBasis:'units'}},
  {id:'orange',name:'Orange Juice',dist:'Merchants',cat:'Mixer',unit:'Case',pack:8,buildTo:72,visionPackaging:{mode:'caseLoose',unitsPerCase:8,unitLabel:'bottles',buildToBasis:'units'}}
];

test('category/vendor context is derived from the selected category only',()=>assert.deepEqual(Vision.context(products),{vendor:'Merchants',category:'Mixer'}));
test('recognition candidates contain only the selected category and vendor',()=>{const catalog=products.concat([{id:'lime',name:'Limes',dist:'Merchants',cat:'Fruit',pack:1},{id:'vodka',name:'Vodka',dist:'Bellows/WI',cat:'Vodka',pack:12}]);const ids=BI.candidates(catalog,Vision.context(products)).map(x=>x.productId);assert.deepEqual(ids,['pine','orange']);});
test('canceling leaves inventory unchanged because application is explicit',()=>{const before={keep:'7','Orange Juice':'4'},out=Vision.applyReviewedCounts(before,[],products);assert.deepEqual(out.counts,before);assert.deepEqual(out.updatedNames,[]);});
test('confirming updates only reviewed known products',()=>{const out=Vision.applyReviewedCounts({'Orange Juice':'4',untouched:'9'},[{productId:'pine',detectedCases:2,detectedLooseUnits:3}],products);assert.equal(out.counts['Pineapple Juice::cases'],'2');assert.equal(out.counts['Pineapple Juice::loose'],'3');assert.equal(out.counts['Orange Juice'],'4');assert.equal(out.counts.untouched,'9');assert.deepEqual(out.updatedNames,['Pineapple Juice']);});
test('unknown and removed products never update inventory',()=>{const out=Vision.applyReviewedCounts({safe:'1'},[{productId:'Unknown',unknown:true,detectedCases:5},{productId:'pine',removed:true,detectedCases:4}],products);assert.deepEqual(out.counts,{safe:'1'});});
test('one photo can return multiple products into one unified review',()=>{const rows=Vision.reviewRows([{productId:'pine',detectedCases:1,detectedLooseUnits:0,confidence:'high',sourcePhotoIds:['a']},{productId:'orange',detectedCases:0,detectedLooseUnits:3,confidence:'medium',sourcePhotoIds:['a']}],products);assert.equal(rows.length,2);assert.deepEqual(rows.map(x=>x.productId),['pine','orange']);});
test('review groups multiple packaging detections by catalog product',()=>{const rows=Vision.reviewRows([{productId:'pine',detectedCases:1,detectedLooseUnits:0,confidence:'high',sourcePhotoIds:['a']},{productId:'pine',detectedCases:0,detectedLooseUnits:3,confidence:'medium',sourcePhotoIds:['b']}],products);assert.equal(rows.length,1);assert.equal(rows[0].detectedCases,1);assert.equal(rows[0].detectedLooseUnits,3);assert.equal(rows[0].confidence,'medium');});
test('unified review summary counts known, review, unknown, and unfinished results',()=>{const rows=[{productId:'pine',confidence:'high'},{productId:'orange',confidence:'medium'},{productId:'Unknown',unknown:true,confidence:'low'}];assert.deepEqual(Vision.reviewSummary(rows,4,1),{productsDetected:2,highConfidence:1,needsReview:1,unknownProducts:1,photosProcessed:3,photosUnfinished:1});});
test('continuous session adds and removes photos without processing early',()=>{const s=Vision.createPhotoSession();s.add({id:'a'});s.add({id:'b'});assert.equal(s.isProcessing(),false);assert.deepEqual(s.remove(0).map(x=>x.id),['b']);assert.equal(s.process(),true);assert.equal(s.isProcessing(),true);assert.equal(s.process(),false);});
test('workflow cannot review or confirm until processing reaches Ready For Review',()=>{const w=Vision.createWorkflow(),rows=[{productId:'pine'}];for(const state of [Vision.WORKFLOW_STATES.PREPARING,Vision.WORKFLOW_STATES.UPLOADING,Vision.WORKFLOW_STATES.ANALYZING,Vision.WORKFLOW_STATES.COMBINING]){w.set(state);assert.equal(w.canReview(),false);assert.equal(w.canConfirm(rows),false);}w.set(Vision.WORKFLOW_STATES.REVIEW);assert.equal(w.canReview(),true);assert.equal(w.canConfirm(rows),true);});
test('confirm remains unavailable when review has no known product',()=>{const w=Vision.createWorkflow();w.set(Vision.WORKFLOW_STATES.REVIEW);assert.equal(w.canConfirm([]),false);assert.equal(w.canConfirm([{productId:'Unknown',unknown:true}]),false);assert.equal(w.canConfirm([{productId:'pine',removed:true}]),false);});
test('completed zero-recognition review has no confirmable products',async()=>{const out=await BI.run({photos:[{id:'empty'}],analyze:()=>({results:[]})}),rows=Vision.reviewRows(out.results,products),w=Vision.createWorkflow();w.set(Vision.WORKFLOW_STATES.REVIEW);assert.equal(out.completedPhotoCount,1);assert.deepEqual(rows,[]);assert.equal(w.canConfirm(rows),false);});
test('retry selects only failed photos and retains successful photos',()=>{const s=Vision.createPhotoSession();s.add({id:'good'});s.add({id:'failed'});s.process();assert.deepEqual(s.failed(['failed']).map(x=>x.id),['failed']);s.resume();assert.deepEqual(s.photos().map(x=>x.id),['good','failed']);});
test('configured loose-unit labels and plain inventory lines are preserved',()=>{const lines=Vision.inventoryLines({detectedCases:1,detectedLooseUnits:5},products[0]);assert.deepEqual(lines,{cases:'1 case',loose:'5 bottles',total:'13 total bottles'});});
test('editable unitsPerCase wins when product.pack differs',()=>{const p={name:'Edited Pack',unit:'Case',pack:6,buildTo:72},cfg={mode:'standard',buildToBasis:'units',countBasis:'units',unitsPerCase:12,unitLabel:'bottles'};assert.equal(Vision.orderQuantity(p,55,cfg),2);assert.equal(Vision.orderExplanation(p,55,cfg,0).unitsPerCase,12);});
test('Island Oasis converts 36 on-hand cartons to a three-case base order',()=>{const p={name:'Island Oasis',unit:'Case',pack:6,buildTo:72},cfg={mode:'caseLoose',buildToBasis:'units',countBasis:'cases',unitsPerCase:12,unitLabel:'cartons'},x=Vision.orderExplanation(p,3,cfg,0);assert.equal(x.counted,36);assert.equal(x.shortage,36);assert.equal(x.baseSuggestedOrder,3);assert.equal(x.suggestedOrder,Vision.orderQuantity(p,3,cfg));assert.match(x.text,/At 12 cartons per case, order 3 cases/);});
test("Tito's rounds a 17-bottle shortage to two configured 12-bottle cases",()=>{const p={name:"Tito's",unit:'Case',pack:6,buildTo:72},cfg={mode:'standard',buildToBasis:'units',countBasis:'units',unitsPerCase:12,unitLabel:'bottles'},x=Vision.orderExplanation(p,55,cfg,0);assert.equal(x.counted,55);assert.equal(x.shortage,17);assert.equal(x.baseSuggestedOrder,2);assert.match(x.text,/ordered by full case/);assert.match(x.text,/rounds up to 2 cases/);});
test('case-basis products are not multiplied or divided as physical units',()=>{const p={name:'Case Basis',unit:'Case',pack:12,buildTo:10},cfg={mode:'standard',buildToBasis:'cases',countBasis:'cases',unitsPerCase:24,unitLabel:'bottles'},x=Vision.orderExplanation(p,4,cfg,0);assert.equal(x.counted,4);assert.equal(x.shortage,6);assert.equal(Vision.orderQuantity(p,4,cfg),6);assert.equal(x.unitsPerCase,1);});
test('manual adjustment is separate from the base build-to recommendation',()=>{const p={name:'Island Oasis',unit:'Case',pack:12,buildTo:72},cfg={mode:'caseLoose',buildToBasis:'units',countBasis:'cases',unitsPerCase:12,unitLabel:'cartons'},x=Vision.orderExplanation(p,3,cfg,1);assert.equal(x.baseSuggestedOrder,3);assert.equal(x.manualAdjustment,1);assert.equal(x.suggestedOrder,4);assert.match(x.text,/order 3 cases/);assert.match(x.text,/Manual adjustment: \+1 case\. Final suggested order: 4 cases/);});
test('visible build-to explanation uses the exact actual order calculation',()=>{const p={name:'Juice',unit:'Case',pack:8,buildTo:72},cfg={mode:'standard',buildToBasis:'units',countBasis:'units',unitsPerCase:12,unitLabel:'bottles'},x=Vision.orderExplanation(p,17,cfg,0);assert.equal(x.suggestedOrder,Vision.orderQuantity(p,17,cfg));assert.equal(x.text,'You have 17 bottles. Your target is 72 bottles. You are short 55 bottles. This item is ordered by full case. PourGrid rounds up to 5 cases.');});
test('saved Lime Juice configuration drives order math and explanation',()=>{const p={name:'Lime Juice',unit:'Case',pack:12,buildTo:8},cfg={mode:'standard',unitsPerCase:12,countBasis:'units',buildToBasis:'units',unitLabel:'bottles'};assert.deepEqual([8,7,0,13].map(n=>Vision.orderQuantity(p,n,cfg)),[0,1,1,0]);assert.equal(Vision.orderExplanation(p,7,cfg,0).text,'You have 7 bottles. Your target is 8 bottles. You are short 1 bottle. This item is ordered by full case. PourGrid rounds up to 1 case.');});
test('Lime Juice Vision counts are stored as total bottles for unit-basis ordering',()=>{const p={id:'lime',name:'Lime Juice',unit:'Case',pack:12,buildTo:8,visionPackaging:{mode:'caseLoose',unitsPerCase:12,countBasis:'units',buildToBasis:'units',unitLabel:'bottles'}},out=Vision.applyReviewedCounts({},[{productId:'lime',detectedCases:0,detectedLooseUnits:0}],[p]);assert.equal(out.counts['Lime Juice::cases'],'0');assert.equal(out.counts['Lime Juice::loose'],'0');assert.equal(out.counts['Lime Juice'],'0');assert.equal(Vision.orderQuantity(p,Number(out.counts['Lime Juice']),p.visionPackaging),1);});
