'use strict';
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto(process.env.PG_E2E_URL,{waitUntil:'domcontentloaded'});
 await page.locator('#pgAuthEmail').fill(process.env.PG_E2E_EMAIL);await page.locator('#pgAuthPassword').fill(process.env.PG_E2E_PASSWORD);await page.locator('#pgAuthSubmit').click();
 await page.locator('#app:not([hidden])').waitFor({timeout:30000});
 const body=await page.locator('body').innerText();assert.match(body,/Full Count|Dashboard/i);assert.match(body,/History/i);assert.match(body,/Profit Lab/i);
 const denied=await page.evaluate(async({org,location})=>{const key=Object.keys(localStorage).find(k=>/^sb-.*-auth-token$/.test(k)),stored=key&&JSON.parse(localStorage.getItem(key)),token=stored?.access_token||stored?.currentSession?.access_token;const response=await fetch(window.POURGRID_CONFIG.supabaseUrl+'/rest/v1/rpc/get_location_order_history_v2',{method:'POST',headers:{apikey:window.POURGRID_CONFIG.supabaseAnonKey,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({p_organization:org,p_location:location,p_limit:1,p_offset:0})});return {ok:response.ok,status:response.status};},{org:process.env.PG_TARGET_ORG,location:process.env.PG_TARGET_LOCATION});
 assert.equal(denied.ok,false,'isolated tenant must not read Sapphire Beach Bar History');assert.ok([400,401,403].includes(denied.status));
 const result=await page.evaluate(async()=>{if(!window.POURGRID_AUTH_CONTEXT||!window.POURGRID_HISTORY_API||!window.POURGRID_PROFIT_LAB_API||!window.PourGridHistory)throw Error('authorized history runtime unavailable');const step=async(name,fn)=>{try{return await fn()}catch(e){throw Error(name+': '+String(e?.message||e?.code||e?.details||'opaque API error'))}},draftId='pr57-'+crypto.randomUUID(),payload={draftId,orderType:'bar',date:'8/23/2026',time:'12:00 AM',counts:{'Isolated Test Rum':5},items:[{productName:'Isolated Test Rum',dist:'Shared / Not specified',physicalCount:5,baseBuildTo:8,adjustedBuildTo:8,calculatedOrderQty:3,manualAdjustment:0,finalOrderQty:3}]};const first=await step('save',()=>window.POURGRID_ORDER_API.save(payload)),retry=await step('retry',()=>window.POURGRID_ORDER_API.save(payload)),rows=await step('history',()=>window.POURGRID_HISTORY_API.list(100,0)),viaProfit=await step('profit-history',()=>window.POURGRID_PROFIT_LAB_API.history(100,0)),normalized=window.PourGridHistory.normalizeHistory(rows),analytics=window.PourGridHistory.analyze(rows);return {first,retry,rowCount:rows.length,profitCount:viaProfit.length,normalized:normalized.filter(x=>x.draftId==='pr57-seeded-history').length,analytics};});
 assert.equal(result.first,result.retry);assert.equal(result.normalized,1);assert.equal(result.rowCount,result.profitCount);assert.equal(result.analytics.confidence,'Low');assert.ok(!errors.some(x=>/history normalizer unavailable|history.*failed/i.test(x)),errors.join('\n'));
 console.log(JSON.stringify({authenticated:true,dashboard:true,history:true,profitLab:true,scopedRows:result.rowCount,dedupedDrafts:1,idempotent:true,confidence:'Low',noVendorEmail:true}));await browser.close();
})().catch(e=>{console.error(e&&e.stack||e);process.exit(1)});
