const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('drink-price-estimator.js','utf8'),html=fs.readFileSync('index.html','utf8');
const products=JSON.parse(html.match(/var PG_V12_PRODUCTS=(\[[\s\S]*?\]);\s*var PRODUCTS=/)[1]);
function coreFor(catalog){const context={window:{PRODUCTS:catalog},document:{getElementById:()=>null,addEventListener:()=>{},querySelector:()=>null,body:{},head:{appendChild:()=>{}},createElement:()=>({})},localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},navigator:{},MutationObserver:function(){this.observe=()=>{}},setInterval:()=>{},setTimeout:()=>{}};vm.runInNewContext(source,context);return context.window.PourGridProfitLabCore;}
test('every active inventory product is represented and round-trips by canonical option ID',()=>{const active=products.filter(p=>p.active!==false),core=coreFor(products),report=core.catalogReport();assert.ok(active.length>100);assert.equal(report.totalActive,active.length);assert.deepEqual(Array.from(report.missingActiveItems),[]);assert.deepEqual(Array.from(report.invalidCategoryAssignments),[]);assert.deepEqual(Array.from(report.optionRoundTripFailures),[]);assert.deepEqual(Array.from(report.selectedIdsAbsent),[]);assert.equal(report.zeroUnexplainedDiscrepancies,true);for(const option of core.unifiedCatalog()){const item={source:option.source,catalogItemId:option.id,catalogCategory:option.category,ingredientId:option.source==='shared'?option.sourceId:'',productName:option.source==='catalog'?option.name:'',name:option.name,amount:1,unit:'oz'};assert.equal(core.catalogSelectionId(item),option.id);assert.match(core.itemOptions(option.category,option.id),/ selected>/);}});
test('Pineapple Juice keeps its source-prefixed canonical ID after rebuild and legacy name fallback',()=>{const fixture=[{catalogId:'juice',name:'Pineapple Juice',cat:'Mixer',dist:'Merchants',bottleMl:1000,pack:1}],core=coreFor(fixture),option=core.unifiedCatalog()[0];assert.equal(option.category,'Merchants');assert.equal(option.id,'catalog:juice');assert.equal(core.catalogSelectionId({source:'catalog',catalogItemId:'catalog:juice',catalogCategory:'Merchants',productName:'Pineapple Juice'}),'catalog:juice');assert.equal(core.catalogSelectionId({source:'catalog',productName:'Pineapple Juice'}),'catalog:juice');assert.match(core.itemOptions('Merchants','catalog:juice'),/value="catalog:juice" selected/);});
test('pointer drag sequence maps continuously to native range steps without root replacement',()=>{const core=coreFor([]),values=[150,175,200,225,250,275,300].map(x=>core.targetFromPointer(x,100,200,5,40,1));assert.deepEqual(values,[14,18,23,27,31,36,40]);assert.match(source,/setPointerCapture\(event\.pointerId\)/);assert.match(source,/releasePointerCapture\(event\.pointerId\)/);assert.match(source,/touch-action:none/);assert.doesNotMatch(source,/function setAmount\(index,value\)[^\n]+render\(\)/);});
test('completed rows use accessible progressive disclosure and invalid rows expand for validation',()=>{assert.match(source,/class="pg-ingredient-summary"/);assert.match(source,/aria-expanded=/);assert.match(source,/pg-ingredient-editor"'\+\(expanded\?'':' hidden'\)/);assert.match(source,/if\(Number\.isInteger\(index\)\)\{expandedRows\.add\(index\);refreshRow\(index\);\}/);assert.match(source,/min-height:64px/);assert.match(source,/min-width:44px;min-height:44px/);});
test('configured vodka products remain data driven and reachable',()=>{const vodka=products.filter(p=>p.cat==='Vodka').map(p=>p.name);for(const expected of ['Stoli Vodka','Stoli Raz','Stoli Oranj','Stoli Blu','Deep Eddy Lemon','Deep Eddy Grapefruit','Ketel One',"Tito's Handmade Vodka"])assert.ok(vodka.includes(expected));assert.doesNotMatch(source,/\[['"]Stoli Vodka['"],['"]Stoli Raz/);});
test('Merchants combines Mixers and Fruit without changing source metadata',()=>{const merchant=products.filter(p=>p.dist==='Merchants'),mixers=merchant.filter(p=>p.cat==='Mixer'),fruit=merchant.filter(p=>p.cat==='Fruit');assert.ok(mixers.length);assert.ok(fruit.length);assert.match(source,/return'Merchants'/);assert.match(source,/sourceMetadata/);assert.equal(merchant.length,mixers.length+fruit.length);});
test('picker hides storage sources and has category then item controls',()=>{assert.match(source,/data-field="catalogCategory"/);assert.match(source,/data-field="catalogItem"/);assert.doesNotMatch(source,/>Shared ingredient<|>PourGrid catalog<|>Custom ingredient</);assert.match(source,/Legacy custom ingredient/);});
test('amount controls are isolated, non-submitting, quarter-step and whole-item safe',()=>{assert.match(source,/data-amount-step/);assert.match(source,/event\.preventDefault/);assert.match(source,/function setAmount\(index,value\)/);assert.match(source,/Math\.round\(numeric\)/);assert.match(source,/Advanced amount/);assert.match(source,/type="button" data-amount/);});
test('catalog core preserves costing math and never treats missing cost as zero',()=>{const core=coreFor([]);assert.equal(typeof core.catalogReport,'function');assert.equal(core.menuRound(10.01),10.5);const result=core.calculate({target:20,ingredients:[{source:'catalog',productName:'Missing Cost',name:'Missing Cost',amount:1,unit:'oz',unitCost:null}]});assert.equal(result.total,0);assert.deepEqual(Array.from(result.missing),['Missing Cost']);});
