const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('drink-price-estimator.js','utf8'),html=fs.readFileSync('index.html','utf8');
const products=JSON.parse(html.match(/var PG_V12_PRODUCTS=(\[[\s\S]*?\]);\s*var PRODUCTS=/)[1]);
test('every active inventory product is represented by the derived catalog',()=>{const active=products.filter(p=>p.active!==false);assert.ok(active.length>100);assert.match(source,/products\(\)\.forEach/);assert.match(source,/if\(p\.active===false\)return/);assert.match(source,/totalActive:all\.length/);});
test('configured vodka products remain data driven and reachable',()=>{const vodka=products.filter(p=>p.cat==='Vodka').map(p=>p.name);for(const expected of ['Stoli Vodka','Stoli Raz','Stoli Oranj','Stoli Blu','Deep Eddy Lemon','Deep Eddy Grapefruit','Ketel One',"Tito's Handmade Vodka"])assert.ok(vodka.includes(expected));assert.doesNotMatch(source,/\[['"]Stoli Vodka['"],['"]Stoli Raz/);});
test('Merchants combines Mixers and Fruit without changing source metadata',()=>{const merchant=products.filter(p=>p.dist==='Merchants'),mixers=merchant.filter(p=>p.cat==='Mixer'),fruit=merchant.filter(p=>p.cat==='Fruit');assert.ok(mixers.length);assert.ok(fruit.length);assert.match(source,/return'Merchants'/);assert.match(source,/sourceMetadata/);assert.equal(merchant.length,mixers.length+fruit.length);});
test('picker hides storage sources and has category then item controls',()=>{assert.match(source,/data-field="catalogCategory"/);assert.match(source,/data-field="catalogItem"/);assert.doesNotMatch(source,/>Shared ingredient<|>PourGrid catalog<|>Custom ingredient</);assert.match(source,/Legacy custom ingredient/);});
test('amount controls are isolated, non-submitting, quarter-step and whole-item safe',()=>{assert.match(source,/data-amount-step/);assert.match(source,/event\.preventDefault/);assert.match(source,/function setAmount\(index,value\)/);assert.match(source,/Math\.round\(numeric\)/);assert.match(source,/Advanced amount/);assert.match(source,/type="button" data-amount/);});
test('catalog core preserves costing math and never treats missing cost as zero',()=>{const context={window:{PRODUCTS:[]},document:{getElementById:()=>null,addEventListener:()=>{},querySelector:()=>null,body:{},head:{appendChild:()=>{}},createElement:()=>({})},localStorage:{getItem:()=>null,setItem:()=>{},removeItem:()=>{}},navigator:{},MutationObserver:function(){this.observe=()=>{}},setInterval:()=>{},setTimeout:()=>{}};vm.runInNewContext(source,context);const core=context.window.PourGridProfitLabCore;assert.equal(typeof core.catalogReport,'function');assert.equal(core.menuRound(10.01),10.5);const result=core.calculate({target:20,ingredients:[{source:'catalog',productName:'Missing Cost',name:'Missing Cost',amount:1,unit:'oz',unitCost:null}]});assert.equal(result.total,0);assert.deepEqual(Array.from(result.missing),['Missing Cost']);});
