const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const analytics=fs.readFileSync('history-analytics.js','utf8'),seasonal=fs.readFileSync('seasonal-profiles.js','utf8'),html=fs.readFileSync('index.html','utf8'),gate=fs.readFileSync('auth-gate.js','utf8'),sql=fs.readFileSync('supabase/migrations/202608220001_history_analytics_seasonal_profiles.sql','utf8'),build=fs.readFileSync('scripts/build-static.mjs','utf8');
function api(){const context={window:{}};vm.runInNewContext(analytics,context);return context.window.PourGridHistory;}
test('seasonal multipliers are bounded deterministic and preserve base zero',()=>{const h=api();assert.equal(h.adjustedBuildTo(10,80),8);assert.equal(h.adjustedBuildTo(10,85),9);assert.equal(h.adjustedBuildTo(0,50),0);assert.throws(()=>h.adjustedBuildTo(10,49));assert.throws(()=>h.adjustedBuildTo(10,151));});
test('authorized APIs support Normal Offseason Peak event and Custom lifecycle',()=>{assert.match(gate,/POURGRID_SEASONAL_API=Object\.freeze/);assert.match(gate,/list_seasonal_profiles/);assert.match(gate,/save_seasonal_profile/);assert.match(gate,/activate_seasonal_profile/);for(const type of ['Offseason','Peak season','Event week','Custom'])assert.match(seasonal,new RegExp(type));});
test('profiles create inactive and activation remains a deliberate manager action',()=>{assert.match(seasonal,/status:'inactive'/);assert.match(seasonal,/data-activate/);assert.match(seasonal,/Activate deliberately/);assert.match(seasonal,/\.activate\(button\.dataset\.activate,null\)/);assert.doesNotMatch(seasonal,/setTimeout\([^)]*activate/);});
test('drafts pin profile snapshots and saved history retains base and adjusted targets',()=>{assert.match(html,/seasonalProfile:pgCurrentSeasonalSnapshot\(\)/);assert.match(html,/record&&!record\.seasonalProfile[\s\S]*pgNormalSeasonalSnapshot/);assert.match(html,/baseBuildTo:p\.buildTo,adjustedBuildTo:adjusted,seasonalProfile:profile/);assert.match(html,/seasonalProfile:activeSession\.seasonalProfile/);assert.match(html,/calculationVersion:"seasonal-build-to-v1\.0\.0"/);});
test('database lifecycle is tenant scoped audited scheduled and overlap safe',()=>{assert.match(sql,/percentage_multiplier between 50 and 150/);assert.match(sql,/created_by uuid/);assert.match(sql,/updated_by uuid/);assert.match(sql,/activated_by uuid/);assert.match(sql,/New profiles must be inactive/);assert.match(sql,/Seasonal Profile dates overlap/);assert.match(sql,/status=case when coalesce\(start_date,v_date\)>v_date then'scheduled'else'active'end/);});
test('Normal 100 remains fail-safe and production build publishes seasonal runtime',()=>{assert.match(seasonal,/Normal 100% remains in effect/);assert.match(seasonal,/NORMAL=Object\.freeze\(\{id:null,name:'Normal'/);assert.match(build,/'seasonal-profiles\.js'/);assert.match(html,/seasonal-profiles\.js\?v=1/);});
test('Profit Lab analytics refuses to manufacture an offseason suggestion',()=>{const result=api().analyze([]);assert.equal(result.suggestedOffseasonPercentage,null);assert.match(result.suggestionReason,/will not manufacture/i);});
