const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const analytics=fs.readFileSync('history-analytics.js','utf8'),seasonal=fs.readFileSync('seasonal-profiles.js','utf8'),html=fs.readFileSync('index.html','utf8'),gate=fs.readFileSync('auth-gate.js','utf8'),sql=fs.readFileSync('supabase/migrations/202608220001_history_analytics_seasonal_profiles.sql','utf8'),managerSql=fs.readFileSync('supabase/migrations/202608240001_seasonal_profile_manager.sql','utf8'),build=fs.readFileSync('scripts/build-static.mjs','utf8');
function api(){const context={window:{}};vm.runInNewContext(analytics,context);return context.window.PourGridHistory;}
test('seasonal multipliers are bounded deterministic and preserve base zero',()=>{const h=api();assert.equal(h.adjustedBuildTo(10,80),8);assert.equal(h.adjustedBuildTo(10,85),9);assert.equal(h.adjustedBuildTo(0,50),0);assert.throws(()=>h.adjustedBuildTo(10,49));assert.throws(()=>h.adjustedBuildTo(10,151));});
test('authorized APIs support Normal Offseason Peak event and Custom lifecycle',()=>{assert.match(gate,/POURGRID_SEASONAL_API=Object\.freeze/);assert.match(gate,/list_seasonal_profiles/);assert.match(gate,/save_seasonal_profile/);assert.match(gate,/activate_seasonal_profile/);for(const type of ['Offseason','Peak season','Event week','Custom'])assert.match(seasonal,new RegExp(type));});
test('profiles use the fixed picker and explicit confirmed save workflow',()=>{for(const type of ['Normal','Offseason','Peak season','Event week','Custom'])assert.match(seasonal,new RegExp(type));assert.match(seasonal,/role="radiogroup"/);assert.match(seasonal,/type="range" min="50" max="150" step="5"/);assert.match(seasonal,/Save & Activate/);assert.match(seasonal,/Save & Schedule/);assert.match(seasonal,/Restore Normal 100%/);assert.match(seasonal,/if\(!s\.confirm\)/);assert.doesNotMatch(seasonal,/New inactive profile|Create inactive profile|pgSeasonalName|pgSeasonalPct|textarea/);});
test('drafts pin profile snapshots and saved history retains base and adjusted targets',()=>{assert.match(html,/seasonalProfile:pgCurrentSeasonalSnapshot\(\)/);assert.match(html,/record&&!record\.seasonalProfile[\s\S]*pgNormalSeasonalSnapshot/);assert.match(html,/baseBuildTo:p\.buildTo,adjustedBuildTo:adjusted,seasonalProfile:profile/);assert.match(html,/seasonalProfile:activeSession\.seasonalProfile/);assert.match(html,/calculationVersion:"seasonal-build-to-v1\.0\.0"/);});
test('database lifecycle is tenant scoped audited scheduled and overlap safe',()=>{assert.match(sql,/percentage_multiplier between 50 and 150/);assert.match(sql,/created_by uuid/);assert.match(sql,/updated_by uuid/);assert.match(sql,/activated_by uuid/);assert.match(managerSql,/has_location_role\(p_organization,p_location,array\['administrator','manager'/);assert.match(managerSql,/Location is outside organization/);assert.match(managerSql,/Seasonal Profile dates overlap/);assert.match(managerSql,/pg_advisory_xact_lock/);assert.match(managerSql,/America\/St_Thomas/);});
test('Normal 100 remains fail-safe and production build publishes seasonal runtime',()=>{assert.match(seasonal,/Normal 100% remains in effect/);assert.match(seasonal,/name:'Normal',profile_type:'Normal',percentage_multiplier:100/);assert.match(build,/'seasonal-profiles\.js'/);assert.match(html,/seasonal-profiles\.js\?v=1/);});
test('Seasonal Profiles stays accessible through Settings without injecting a Home card',()=>{assert.match(seasonal,/g\.pgOpenSeasonalProfiles=open/);assert.doesNotMatch(seasonal,/pgSeasonalTrigger|pg-home-body/);assert.match(html,/pgSettingsRow\("◫","Seasonal Profiles",[\s\S]*,"seasonal"\)/);assert.match(html,/window\.pgOpenSeasonalProfiles/);});
test('Profit Lab analytics refuses to manufacture an offseason suggestion',()=>{const result=api().analyze([]);assert.equal(result.suggestedOffseasonPercentage,null);assert.match(result.suggestionReason,/will not manufacture/i);});
test('seasonal list union is wrapped before deterministic ordering',()=>{const repair=fs.readFileSync('supabase/migrations/202608230002_seasonal_list_order_repair.sql','utf8');assert.match(repair,/from \([\s\S]*union all[\s\S]*\)q order by q\.is_effective desc,q\.name/);assert.doesNotMatch(repair,/insert into|update public\.seasonal_profiles|delete from|truncate/i);});
