export const AUTH_STATES=Object.freeze({INITIALIZING:'initializing',SIGNED_OUT:'signed_out',CALLBACK:'callback',LOADING_CONTEXT:'loading_context',PENDING:'pending',AUTHORIZED:'authorized',AUTH_ERROR:'auth_error',CONTEXT_ERROR:'context_error'});
export const ROLES=Object.freeze(['administrator','manager','bar_lead','inventory_staff','read_only_viewer']);
export const AUTH_CONTEXT_KEY='pourgrid-auth-context-v1';
const CALLBACK_KEYS=new Set(['code','token','token_hash','access_token','refresh_token','expires_in','expires_at','type','error','error_code','error_description','error_uri','sb']),CALLBACK_MARKERS=new Set(['code','token','token_hash','access_token','refresh_token','error','error_code','error_description','error_uri']);
export function readAuthCallback(locationLike){const search=new URLSearchParams(String(locationLike?.search||'').replace(/^\?/,'')),hash=new URLSearchParams(String(locationLike?.hash||'').replace(/^#/,'')),keys=[...search.keys(),...hash.keys()],present=keys.some(key=>CALLBACK_MARKERS.has(key));if(!present)return {present:false,invalid:false,code:null};const code=search.get('code'),hasError=['error','error_code','error_description'].some(key=>search.has(key)||hash.has(key)),invalid=hasError||!code||[...hash.keys()].some(key=>CALLBACK_KEYS.has(key));return {present:true,invalid,code:invalid?null:code}}
export function readRecoverySession(locationLike){const hash=new URLSearchParams(String(locationLike?.hash||'').replace(/^#/,''));if(hash.get('type')!=='recovery')return null;const access_token=hash.get('access_token'),refresh_token=hash.get('refresh_token');return access_token&&refresh_token?{access_token,refresh_token}:null}
export function cleanAuthCallback(historyLike,locationLike){const origin=String(locationLike?.origin||''),pathname=String(locationLike?.pathname||'/')||'/';historyLike.replaceState(null,'',origin+pathname);return origin+pathname}
export function isCallbackLocation(locationLike){return readAuthCallback(locationLike).present}
export function otpOutcome(error){if(!error)return {ok:true,message:'Check your email for a secure PourGrid sign-in link.'};const value=String(error.message||error);if(/rate|too many|429/i.test(value))return {ok:false,retryable:false,message:'Too many sign-in emails were requested. Wait a few minutes, then try once.'};if(/network|fetch|offline|load failed|timeout/i.test(value))return {ok:false,retryable:true,message:'PourGrid could not reach secure sign-in. It will retry automatically.'};if(/email|smtp|provider|send/i.test(value))return {ok:false,retryable:true,message:'Secure email delivery is temporarily unavailable. PourGrid will retry automatically.'};return {ok:false,retryable:false,message:'Secure sign-in is temporarily unavailable. Try again shortly.'}}
export function capabilities(role){return {view:ROLES.includes(role),mutate:['administrator','manager','bar_lead','inventory_staff'].includes(role),order:['administrator','manager','bar_lead','inventory_staff'].includes(role),receive:['administrator','manager','bar_lead','inventory_staff'].includes(role),approve:['administrator','manager'].includes(role),baseline:['administrator','manager'].includes(role),reconcile:['administrator','manager'].includes(role),admin:role==='administrator'}}
export function isNetworkAuthError(error){const status=Number(error?.status||error?.statusCode)||0,code=String(error?.code||error?.error_code||''),message=String(error?.message||error||'');return status===502||status===503||status===504||/PGRST00[012]|PGRST504/i.test(code+' '+message)||/fetch|network|offline|load failed|connection|timeout|schema cache|service unavailable|temporarily unavailable|database unavailable/i.test(message)}
export function saveAuthorizationContext(storage,userId,context,now=Date.now()){if(!storage||!userId||!context?.organizationId||!context?.locationId||!ROLES.includes(context.role))return false;const value={version:1,userId,verifiedAt:now,organizationId:context.organizationId,organizationName:String(context.organizationName||''),locationId:context.locationId,locationName:String(context.locationName||''),role:context.role};storage.setItem(AUTH_CONTEXT_KEY,JSON.stringify(value));return true}
export function readAuthorizationContext(storage,userId){try{const value=JSON.parse(storage?.getItem(AUTH_CONTEXT_KEY)||'null');if(value?.version!==1||value.userId!==userId||!value.organizationId||!value.locationId||!value.organizationName||!value.locationName||!ROLES.includes(value.role)||!Number.isFinite(value.verifiedAt))return null;return Object.freeze({...value,capabilities:capabilities(value.role)})}catch{return null}}
export function clearAuthorizationContext(storage){storage?.removeItem(AUTH_CONTEXT_KEY);storage?.removeItem('pourgrid-selected-location')}
export function authorizeContext(input,preferredLocation){const memberships=Array.isArray(input?.memberships)?input.memberships:[],organizations=Array.isArray(input?.organizations)?input.organizations:[],locations=Array.isArray(input?.locations)?input.locations:[],links=Array.isArray(input?.locationMemberships)?input.locationMemberships:[];const orgById=new Map(organizations.map(x=>[x.id,x])),locationById=new Map(locations.map(x=>[x.id,x]));const contexts=[];for(const membership of memberships){if(!membership||!membership.id||!membership.organization_id||!ROLES.includes(membership.role))continue;const org=orgById.get(membership.organization_id);if(!org)continue;for(const link of links.filter(x=>x.membership_id===membership.id)){const location=locationById.get(link.location_id);if(location&&location.organization_id===membership.organization_id)contexts.push({organizationId:org.id,organizationName:org.name,locationId:location.id,locationName:location.name,role:membership.role,capabilities:capabilities(membership.role)})}}if(!contexts.length)return {state:AUTH_STATES.PENDING,contexts:[]};const selected=contexts.find(x=>x.locationId===preferredLocation)||(contexts.length===1?contexts[0]:null);return {state:selected?AUTH_STATES.AUTHORIZED:AUTH_STATES.LOADING_CONTEXT,contexts,selected}}
export async function loadAuthorization(adapter,userId,preferredLocation){const memberships=await adapter.memberships(userId);if(!memberships.length)return {state:AUTH_STATES.PENDING,contexts:[]};const orgIds=[...new Set(memberships.map(x=>x.organization_id))],membershipIds=memberships.map(x=>x.id);const [organizations,locationMemberships]=await Promise.all([adapter.organizations(orgIds),adapter.locationMemberships(membershipIds)]);const locationIds=[...new Set(locationMemberships.map(x=>x.location_id))],locations=locationIds.length?await adapter.locations(locationIds):[];return authorizeContext({memberships,organizations,locationMemberships,locations},preferredLocation)}
export function clearSessionState(storage){clearAuthorizationContext(storage)}
