import {createClient} from '@supabase/supabase-js';
import {AUTH_STATES,readAuthCallback,cleanAuthCallback,loadAuthorization,clearSessionState,otpOutcome,isNetworkAuthError,saveAuthorizationContext,readAuthorizationContext,clearAuthorizationContext} from './auth-state.mjs';

const root=document.getElementById('pgAuthRoot'),app=document.getElementById('app'),config=window.POURGRID_CONFIG||{};
let client=null,inviteClient=null,busy=false,authorized=false,authSubscription=null,initializing=false,reauthorizeTimer=null;
function lockApp(){authorized=false;app.hidden=true;root.hidden=false;document.body.classList.remove('pg-booting');document.body.classList.add('pg-auth-pending');document.querySelector('.pg-auth-signout')?.remove()}
function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function frame(title,body,actions=''){root.hidden=false;root.innerHTML=`<main class="pg-auth"><section class="pg-auth-card"><div class="pg-auth-mark" aria-hidden="true"><span></span><span></span><span></span><span></span></div><div class="pg-auth-kicker">POURGRID</div><h1>${esc(title)}</h1>${body}${actions}</section></main>`}
function loading(message='Checking your secure session…'){lockApp();frame('Getting PourGrid ready',`<p class="pg-auth-copy" role="status">${esc(message)}</p><div class="pg-auth-loader" aria-hidden="true"></div>`)}
function authForm(title,message,buttonLabel='Email me a secure sign-in link',alert=false){frame(title,`<p class="pg-auth-copy"${alert?' role="alert" aria-live="assertive"':''}>${esc(message)}</p><form id="pgAuthForm" novalidate><label for="pgAuthEmail">Work email</label><input id="pgAuthEmail" name="email" type="email" inputmode="email" autocomplete="email" required placeholder="name@example.com"><div id="pgAuthMessage" class="pg-auth-message" role="alert" aria-live="polite"></div><button id="pgAuthSubmit" type="submit">${esc(buttonLabel)}</button></form><p class="pg-auth-fine">Access still requires an active PourGrid organization, location, and role.</p>`);const form=document.getElementById('pgAuthForm');form.addEventListener('submit',requestOtp);document.getElementById('pgAuthEmail').focus()}
function signedOut(message='Use your work email. Receiving a link does not grant operational access.'){authForm('Sign in to PourGrid',message)}
function invalidLink(){lockApp();authForm('Sign-in link is invalid or expired','This secure sign-in link is invalid, expired, or has already been used. Request a new link to continue.','Email me a new sign-in link',true)}
function errorState(kind,message){frame(kind==='auth'?'Sign-in could not be completed':'Access check unavailable',`<p class="pg-auth-copy" role="alert">${esc(message)}</p>`,`<button id="pgAuthRetry" class="pg-auth-secondary">Try again</button>`);document.getElementById('pgAuthRetry').onclick=initialize}
function pending(){frame('Access pending','<p class="pg-auth-copy">Your account is signed in, but active PourGrid access has not been assigned. Ask your manager to confirm your organization, location, and role.</p>','<button id="pgAuthSignOut" class="pg-auth-secondary">Sign out</button>');document.getElementById('pgAuthSignOut').onclick=signOut}
function chooseLocation(result){frame('Choose a location','<p class="pg-auth-copy">Select one of your authorized locations.</p><div class="pg-auth-locations">'+result.contexts.map(x=>`<button data-location="${esc(x.locationId)}">${esc(x.locationName)}</button>`).join('')+'</div>','<button id="pgAuthSignOut" class="pg-auth-link">Sign out</button>');root.querySelectorAll('[data-location]').forEach(button=>button.onclick=()=>{localStorage.setItem('pourgrid-selected-location',button.dataset.location);authorizeCurrent()});document.getElementById('pgAuthSignOut').onclick=signOut}
async function requestOtp(event){event.preventDefault();if(busy)return;const email=document.getElementById('pgAuthEmail').value.trim(),message=document.getElementById('pgAuthMessage'),button=document.getElementById('pgAuthSubmit');if(!/^\S+@\S+\.\S+$/.test(email)){message.textContent='Enter a valid email address.';return}busy=true;button.disabled=true;button.textContent='Sending…';try{const redirectTo=new URL(location.pathname,location.origin).href;const {error}=await client.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});if(error)throw error;const result=otpOutcome();message.className='pg-auth-message success';message.textContent=result.message;button.textContent='Link sent'}catch(error){const result=otpOutcome(error);message.textContent=result.message;button.disabled=false;button.textContent='Email me a secure sign-in link'}finally{busy=false}}
function adapter(){const read=async(table,columns,filter,values)=>{let query=client.from(table).select(columns);if(filter)query=query.in(filter,values);const {data,error}=await query;if(error)throw error;return data||[]};return {memberships:async userId=>{const {data,error}=await client.from('memberships').select('id,organization_id,role').eq('user_id',userId);if(error)throw error;return data||[]},organizations:ids=>read('organizations','id,name','id',ids),locationMemberships:ids=>read('location_memberships','membership_id,location_id','membership_id',ids),locations:ids=>read('locations','id,organization_id,name','id',ids)}}
function removeAdminAccess(){window.POURGRID_ADMIN_API=null;document.getElementById('pgTeamAccess')?.remove();document.getElementById('pgTeamModal')?.remove()}
async function applyAuthorizedContext(context,userId,{cached=false}={}){const current=Object.freeze({...context});window.POURGRID_AUTH_CONTEXT=current;if(!cached)saveAuthorizationContext(localStorage,userId,current);localStorage.setItem('pourgrid-selected-location',current.locationId);if(authorized){if(current.capabilities?.admin)installAdminAccess(current);else removeAdminAccess();return}await startProtectedApp()}
async function restoreCachedAuthorization(session,error){if(!session?.user?.id||!isNetworkAuthError(error))return false;const cached=readAuthorizationContext(localStorage,session.user.id);if(!cached)return false;await applyAuthorizedContext(cached,session.user.id,{cached:true});return true}
async function authorizeCurrent(callbackAttempt=false,silent=false){if(!silent)loading(callbackAttempt?'Completing your secure sign-in…':'Restoring your secure session…');const {data:{session},error}=await client.auth.getSession();if(error||!session){if(await restoreCachedAuthorization(session,error))return;if(callbackAttempt){invalidLink();return}lockApp();clearAuthorizationContext(localStorage);signedOut(error&&!isNetworkAuthError(error)?'Your session is invalid or expired. Request a new sign-in link.':undefined);return}const {data:{user},error:userError}=await client.auth.getUser();if(userError||!user){if(await restoreCachedAuthorization(session,userError))return;await client.auth.signOut({scope:'local'});clearAuthorizationContext(localStorage);if(callbackAttempt){invalidLink();return}lockApp();signedOut('Your session is invalid or expired. Request a new sign-in link.');return}try{const acceptance=await client.rpc('accept_access_invitation');if(acceptance.error&&!/function|schema cache|PGRST202/i.test(String(acceptance.error.message||acceptance.error)))throw acceptance.error;const preferred=localStorage.getItem('pourgrid-selected-location')||'',result=await loadAuthorization(adapter(),user.id,preferred);if(result.state===AUTH_STATES.PENDING){clearAuthorizationContext(localStorage);lockApp();pending();return}if(!result.selected){clearAuthorizationContext(localStorage);lockApp();chooseLocation(result);return}await applyAuthorizedContext(result.selected,user.id)}catch(error){if(await restoreCachedAuthorization(session,error))return;lockApp();errorState('context','PourGrid could not confirm your access. No operational data has been opened. Retry when connected.') }}
async function startProtectedApp(){if(authorized)return;const context=window.POURGRID_AUTH_CONTEXT;if(!context?.organizationId||!context?.locationId||!String(context.locationName||'').trim())throw new Error('Authorized location context unavailable');authorized=true;root.hidden=true;app.hidden=false;document.body.classList.remove('pg-auth-pending');for(const source of document.querySelectorAll('script[type="text/pourgrid-protected"]')){await new Promise((resolve,reject)=>{const script=document.createElement('script');for(const attr of source.attributes)if(!['type','data-pg-protected'].includes(attr.name))script.setAttribute(attr.name,attr.value);if(source.src){script.onload=resolve;script.onerror=reject}else{script.textContent=source.textContent}source.after(script);if(!source.src)resolve()})}const signOutButton=document.createElement('button');signOutButton.className='pg-auth-signout';signOutButton.textContent='Sign out';signOutButton.onclick=signOut;document.body.appendChild(signOutButton);if(context.capabilities?.admin)installAdminAccess(context)}

function rpc(name,args={}){return client.rpc(name,args).then(({data,error})=>{if(error)throw error;return data})}
async function sendInviteLink(email){const redirectTo=new URL(location.pathname,location.origin).href,{error}=await inviteClient.auth.signInWithOtp({email,options:{emailRedirectTo:redirectTo}});if(error)throw error}
function adminApi(context){return Object.freeze({list:()=>rpc('admin_list_invitations',{p_organization:context.organizationId,p_location:context.locationId}),async invite(email){const value=await rpc('admin_create_invitation',{p_organization:context.organizationId,p_location:context.locationId,p_email:email,p_role:'bar_lead'});await sendInviteLink(value.email);return value},async resend(item){const value=await rpc('admin_resend_invitation',{p_invitation:item.id});await sendInviteLink(value.email);return value},revoke:id=>rpc('admin_revoke_invitation',{p_invitation:id}),changeRole:(userId,role)=>rpc('admin_change_member_role',{p_organization:context.organizationId,p_user:userId,p_role:role})})}
function installAdminAccess(context){if(!context.capabilities?.admin||document.getElementById('pgTeamAccess'))return;const api=adminApi(context);window.POURGRID_ADMIN_API=api;const trigger=document.createElement('button');trigger.id='pgTeamAccess';trigger.className='pg-team-trigger';trigger.type='button';trigger.textContent='Team access';trigger.setAttribute('aria-haspopup','dialog');trigger.onclick=()=>openTeamAccess(api,context);document.body.appendChild(trigger)}
async function openTeamAccess(api,context){if(!window.POURGRID_AUTH_CONTEXT?.capabilities?.admin||api!==window.POURGRID_ADMIN_API)return;let modal=document.getElementById('pgTeamModal');if(!modal){modal=document.createElement('div');modal.id='pgTeamModal';modal.className='pg-team-backdrop';modal.innerHTML=`<section class="pg-team-dialog" role="dialog" aria-modal="true" aria-labelledby="pgTeamTitle"><header><div><small>ADMINISTRATOR</small><h2 id="pgTeamTitle">Team access</h2><p>${esc(context.organizationName)} · ${esc(context.locationName)}</p></div><button type="button" data-close aria-label="Close team access">×</button></header><form id="pgInviteForm"><label for="pgInviteEmail">Bar Lead email</label><div class="pg-team-form-row"><input id="pgInviteEmail" type="email" autocomplete="email" required placeholder="lead@example.com"><button type="submit">Invite</button></div><p class="pg-team-note">Bar Leads can count, prepare Merchants and bar orders, and receive deliveries. They cannot administer access, approve exceptions, reconcile inventory, or create a baseline.</p><div id="pgTeamMessage" role="status" aria-live="polite"></div></form><div id="pgTeamList" class="pg-team-list" aria-live="polite"></div></section>`;document.body.appendChild(modal);modal.querySelector('[data-close]').onclick=()=>{modal.hidden=true;document.getElementById('pgTeamAccess')?.focus()};modal.onclick=e=>{if(e.target===modal){modal.hidden=true;document.getElementById('pgTeamAccess')?.focus()}};modal.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.hidden=true;document.getElementById('pgTeamAccess')?.focus()}});modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=modal.querySelector('input'),message=modal.querySelector('#pgTeamMessage'),button=e.submitter;button.disabled=true;message.textContent='Sending secure invitation…';try{await api.invite(input.value.trim());input.value='';message.textContent='Invitation sent. The recipient must open the newest sign-in link.';await renderInvitations(api,modal)}catch(error){message.textContent=String(error.message||error)}finally{button.disabled=false}}}modal.hidden=false;modal.querySelector('input').focus();await renderInvitations(api,modal)}
async function renderInvitations(api,modal){const list=modal.querySelector('#pgTeamList');list.textContent='Loading access…';try{const items=await api.list();list.innerHTML=items.length?items.map(item=>`<article class="pg-team-item"><div><strong>${esc(item.email)}</strong><span>${esc(item.role.replaceAll('_',' '))} · ${esc(item.state)}</span></div>${item.state==='pending'||item.state==='expired'?`<div><button type="button" data-resend="${esc(item.id)}">Resend</button><button type="button" data-revoke="${esc(item.id)}">Revoke</button></div>`:item.state==='accepted'&&item.accepted_by?`<label>Role <select data-member="${esc(item.accepted_by)}"><option value="bar_lead"${item.role==='bar_lead'?' selected':''}>Bar Lead</option><option value="inventory_staff"${item.role==='inventory_staff'?' selected':''}>Inventory staff</option><option value="read_only_viewer"${item.role==='read_only_viewer'?' selected':''}>Read-only viewer</option></select></label>`:''}</article>`).join(''):'<p>No invitations yet.</p>';list.querySelectorAll('[data-resend]').forEach(button=>button.onclick=async()=>{button.disabled=true;const item=items.find(value=>value.id===button.dataset.resend);try{await api.resend(item);await renderInvitations(api,modal)}finally{button.disabled=false}});list.querySelectorAll('[data-revoke]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await api.revoke(button.dataset.revoke);await renderInvitations(api,modal)}finally{button.disabled=false}});list.querySelectorAll('[data-member]').forEach(select=>select.onchange=async()=>{select.disabled=true;try{await api.changeRole(select.dataset.member,select.value);await renderInvitations(api,modal)}finally{select.disabled=false}})}catch(error){list.textContent=String(error.message||error)}}
async function signOut(){if(busy)return;busy=true;lockApp();try{await client.auth.signOut()}finally{clearSessionState(localStorage);window.POURGRID_AUTH_CONTEXT=null;location.replace(new URL(location.pathname,location.origin).href)}}
function queueAuthorizationCheck(delay=0){if(initializing||!client)return;clearTimeout(reauthorizeTimer);reauthorizeTimer=setTimeout(()=>authorizeCurrent(false,true),delay)}
function installSessionLifecycle(){window.addEventListener('online',()=>queueAuthorizationCheck(150));window.addEventListener('pageshow',()=>queueAuthorizationCheck(150));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')queueAuthorizationCheck(150)});setInterval(()=>{if(document.visibilityState==='visible')queueAuthorizationCheck()},300000)}
async function initialize(){let callback=readAuthCallback(location),callbackAttempt=callback.present,code=callback.code;if(callbackAttempt)cleanAuthCallback(history,location);loading(callbackAttempt?'Completing your secure sign-in…':'Restoring your secure session…');if(!config.supabaseUrl||!config.supabaseAnonKey){errorState('auth','PourGrid authentication is not configured for this environment.');return}if(callback.invalid){invalidLink();return}initializing=true;try{client=createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,flowType:'pkce',storage:window.localStorage}});inviteClient=createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,flowType:'pkce'}});if(authSubscription)authSubscription.unsubscribe();authSubscription=client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||(!session&&event==='TOKEN_REFRESHED')){lockApp();clearSessionState(localStorage);window.POURGRID_AUTH_CONTEXT=null;removeAdminAccess();signedOut('Your session ended. Request a new secure sign-in link.');return}if(['SIGNED_IN','TOKEN_REFRESHED','USER_UPDATED'].includes(event))queueMicrotask(()=>queueAuthorizationCheck(100))}).data.subscription;if(callbackAttempt){const {error}=await client.auth.exchangeCodeForSession(code);code=null;callback=null;if(error){invalidLink();return}}await authorizeCurrent(callbackAttempt)}catch(error){code=null;callback=null;if(callbackAttempt){invalidLink();return}lockApp();errorState('auth','PourGrid could not initialize authentication. Check your connection and retry.')}finally{initializing=false}}
installSessionLifecycle();
initialize();
