import {createClient} from '@supabase/supabase-js';
import {loadAuthorization} from './auth-state.mjs';

// The app and its on-device history never depend on Supabase availability. An existing
// session is attached in the background for shared drafts and cloud backup only.
const root=document.getElementById('pgAuthRoot'),app=document.getElementById('app'),config=window.POURGRID_CONFIG||{},boot=window.POURGRID_BOOT||{mark(){},settle(){}};
const REQUEST_TIMEOUT_MS=8000;
let client=null;
function wait(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
function withTimeout(promise,ms,message){let timer;return Promise.race([promise,new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(message)),ms)})]).finally(()=>clearTimeout(timer))}
function uuid(value){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value||''))}
function capabilities(){return {view:true,mutate:true,approve:true,baseline:true,reconcile:true,admin:true}}
function storedContexts(){
  try{const rows=JSON.parse(localStorage.getItem('pourgrid-authorized-contexts-v1')||'[]');if(Array.isArray(rows)&&rows.length)return rows}catch(error){}
  try{const registry=JSON.parse(localStorage.getItem('pourgrid-property-registry-v1')||'null');if(registry&&registry.properties)return Object.values(registry.properties).map(property=>({organizationId:property.organizationId,organizationName:property.organizationName,locationId:property.id,locationName:property.locationName||property.displayName})).filter(row=>row.locationId)}catch(error){}
  return [];
}
function localContext(){const rows=storedContexts(),preferred=localStorage.getItem('pourgrid-selected-location')||'',found=rows.find(row=>String(row.locationId)===preferred)||rows[0];return Object.freeze(Object.assign({organizationId:'local-sapphire',organizationName:'Sapphire Beach Bar',locationId:'local-sapphire',locationName:'Sapphire Beach Bar',role:'manager'},found||{},{capabilities:capabilities()}))}
function publishContext(context,contexts){const current=Object.freeze(Object.assign({},context,{capabilities:capabilities()}));window.POURGRID_AUTH_CONTEXT=current;window.POURGRID_AUTH_CONTEXTS=(Array.isArray(contexts)&&contexts.length?contexts:[current]).map(row=>Object.assign({},row,{capabilities:capabilities()}));if(uuid(current.locationId))localStorage.setItem('pourgrid-selected-location',current.locationId);return current}
function rpc(name,args={}){if(!client)return Promise.reject(new Error('Cloud connection unavailable'));return withTimeout(client.rpc(name,args),REQUEST_TIMEOUT_MS,`${name} request timeout`).then(({data,error})=>{if(error)throw error;return data})}
function installOperationalApis(context){
  if(!client||!uuid(context.organizationId)||!uuid(context.locationId))return false;
  const scope={p_organization:context.organizationId,p_location:context.locationId};
  window.POURGRID_HISTORY_API=Object.freeze({list:(limit=100,offset=0)=>rpc('get_location_order_history_v2',{...scope,p_limit:limit,p_offset:offset})});
  window.POURGRID_ORDER_API=Object.freeze({save:order=>rpc('save_location_order',{...scope,p_draft_id:order?.draftId,p_order:order})});
  window.POURGRID_SHARED_DRAFT_API=Object.freeze({open:(workspace,seasonal)=>rpc('open_shared_location_draft',{...scope,p_workspace:workspace,p_seasonal_snapshot:seasonal}),read:workspace=>rpc('read_shared_location_draft',{...scope,p_workspace:workspace}),update:(draft,product,field,value,expected,key)=>rpc('update_shared_draft_field',{...scope,p_draft:draft,p_product_key:product,p_field_key:field,p_value:value,p_expected_field_revision:expected,p_idempotency_key:key}),resolve:(conflict,resolution,draft,product,field)=>rpc('resolve_shared_draft_conflict',{...scope,p_conflict:conflict||null,p_resolution:resolution,p_draft:draft,p_product_key:product,p_field_key:field}),importLegacy:(workspace,legacyId,fields,seasonal,key)=>rpc('import_legacy_shared_draft',{...scope,p_workspace:workspace,p_legacy_draft_id:legacyId,p_fields:fields,p_seasonal_snapshot:seasonal,p_idempotency_key:key}),review:draft=>rpc('review_shared_location_draft',{...scope,p_draft:draft}),finalize:(draft,revision,order)=>rpc('finalize_shared_location_draft',{...scope,p_draft:draft,p_reviewed_revision:revision,p_order:order}),abandon:draft=>rpc('abandon_shared_location_draft',{...scope,p_draft:draft}),heartbeat:(draft,session)=>rpc('heartbeat_shared_draft',{...scope,p_draft:draft,p_session:session}),presence:draft=>rpc('list_shared_draft_presence',{...scope,p_draft:draft}),subscribe:(draft,onChange)=>{const channel=client.channel(`shared-draft-${draft}`).on('postgres_changes',{event:'*',schema:'public',table:'shared_location_drafts',filter:`id=eq.${draft}`},onChange).on('postgres_changes',{event:'*',schema:'public',table:'shared_draft_fields',filter:`draft_id=eq.${draft}`},onChange);client.auth.getSession().then(({data})=>{if(data.session?.access_token)client.realtime.setAuth(data.session.access_token);channel.subscribe()});return channel}});
  window.POURGRID_SEASONAL_API=Object.freeze({list:()=>rpc('list_seasonal_profiles',{...scope,p_on_date:null}),save:profile=>rpc('save_seasonal_profile',{...scope,p_profile:profile}),activate:(id,date)=>rpc('activate_seasonal_profile',{...scope,p_profile:id,p_effective_date:date})});
  window.POURGRID_PROFIT_LAB_API=Object.freeze({history:(limit=100,offset=0)=>window.POURGRID_HISTORY_API.list(limit,offset),list:()=>rpc('list_profit_lab_recipes',scope),save:recipe=>rpc('save_profit_lab_recipe',{...scope,p_recipe:recipe}),remove:id=>rpc('delete_profit_lab_recipe',{...scope,p_recipe:id}),archive:(id,archived)=>rpc('archive_profit_lab_recipe',{...scope,p_recipe:id,p_archived:archived}),revisions:id=>rpc('list_profit_lab_recipe_revisions',{...scope,p_recipe:id}),ingredients:()=>rpc('list_profit_lab_ingredients',scope),saveIngredient:ingredient=>rpc('save_profit_lab_ingredient',{...scope,p_ingredient:ingredient}),importCurrentMenu:recipes=>rpc('import_profit_lab_current_menu',{...scope,p_recipes:recipes,p_source_file:'Sapphire Beach Bar Order Guide v12.xlsx',p_source_version:'v12'})});
  window.pgSubscribeSeasonalProfiles=function(onChange){if(typeof onChange!=='function')return null;const filter=`location_id=eq.${context.locationId}`,channel=client.channel(`seasonal-${context.locationId}`).on('postgres_changes',{event:'*',schema:'public',table:'seasonal_profiles',filter},onChange);client.auth.getSession().then(({data})=>{if(data.session?.access_token)client.realtime.setAuth(data.session.access_token);channel.subscribe()});return()=>client.removeChannel(channel)};
  return true;
}
async function executeProtectedSource(source,asset){let code=source.textContent;if(source.src){const response=await withTimeout(fetch(source.src,{cache:'no-store',credentials:'same-origin'}),5000,`Asset timeout: ${asset}`);if(!response.ok)throw new Error(`Asset failed: ${asset}`);code=await response.text()}await wait(0);const script=document.createElement('script');script.dataset.pgRuntime='true';script.textContent=code;source.after(script);source.dataset.pgLoaded='true'}
async function startApp(){publishContext(localContext());let index=0;for(const source of document.querySelectorAll('script[type="text/pourgrid-protected"]')){if(source.dataset.pgLoaded==='true')continue;const asset=source.src?new URL(source.src,location.href).pathname:`inline-${++index}`;await executeProtectedSource(source,asset)}app.hidden=false;root.hidden=true;document.body.classList.remove('pg-auth-pending','pg-booting');boot.settle('dashboard-visible')}
function adapter(){const read=async(table,columns,filter,values)=>{let query=client.from(table).select(columns);if(filter)query=query.in(filter,values);const {data,error}=await withTimeout(query,REQUEST_TIMEOUT_MS,`${table} request timeout`);if(error)throw error;return data||[]};return {memberships:async userId=>{const {data,error}=await withTimeout(client.from('memberships').select('id,organization_id,role').eq('user_id',userId),REQUEST_TIMEOUT_MS,'Membership request timeout');if(error)throw error;return data||[]},organizations:ids=>read('organizations','id,name','id',ids),locationMemberships:ids=>read('location_memberships','membership_id,location_id','membership_id',ids),locations:ids=>read('locations','id,organization_id,name','id',ids)}}
async function attachExistingSession(){if(!config.supabaseUrl||!config.supabaseAnonKey)return;try{const noBlockingLock=async(_name,_timeout,fn)=>fn();client=createClient(config.supabaseUrl,config.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storage:window.localStorage,lock:noBlockingLock}});installOperationalApis(window.POURGRID_AUTH_CONTEXT||localContext());const {data,error}=await withTimeout(client.auth.getSession(),REQUEST_TIMEOUT_MS,'Background session timeout');if(error||!data?.session)return;const preferred=localStorage.getItem('pourgrid-selected-location')||'',result=await loadAuthorization(adapter(),data.session.user.id,preferred);if(!result.selected)return;const current=publishContext(result.selected,result.contexts);installOperationalApis(current);window.dispatchEvent(new CustomEvent('pourgrid:cloud-ready'))}catch(error){console.warn('[PourGrid cloud optional]',String(error?.message||error))}}
startApp().then(()=>attachExistingSession()).catch(error=>{console.error('[PourGrid startup]',error);app.hidden=false;root.hidden=true;document.body.classList.remove('pg-auth-pending','pg-booting')});
