export const AUTH_STATES=Object.freeze({INITIALIZING:'initializing',SIGNED_OUT:'signed_out',CALLBACK:'callback',LOADING_CONTEXT:'loading_context',PENDING:'pending',AUTHORIZED:'authorized',AUTH_ERROR:'auth_error',CONTEXT_ERROR:'context_error'});
export const ROLES=Object.freeze(['administrator','manager','inventory_staff','read_only_viewer']);
const CALLBACK_KEYS=new Set(['code','token','token_hash','access_token','refresh_token','expires_in','expires_at','type','error','error_code','error_description','error_uri','sb']),CALLBACK_MARKERS=new Set(['code','token','token_hash','access_token','refresh_token','error','error_code','error_description','error_uri']);
export function readAuthCallback(locationLike){const search=new URLSearchParams(String(locationLike?.search||'').replace(/^\?/,'')),hash=new URLSearchParams(String(locationLike?.hash||'').replace(/^#/,'')),keys=[...search.keys(),...hash.keys()],present=keys.some(key=>CALLBACK_MARKERS.has(key));if(!present)return {present:false,invalid:false,code:null};const code=search.get('code'),hasError=['error','error_code','error_description'].some(key=>search.has(key)||hash.has(key)),invalid=hasError||!code||[...hash.keys()].some(key=>CALLBACK_KEYS.has(key));return {present:true,invalid,code:invalid?null:code}}
export function cleanAuthCallback(historyLike,locationLike){const origin=String(locationLike?.origin||''),pathname=String(locationLike?.pathname||'/')||'/';historyLike.replaceState(null,'',origin+pathname);return origin+pathname}
export function isCallbackLocation(locationLike){return readAuthCallback(locationLike).present}
export function otpOutcome(error){if(!error)return {ok:true,message:'Check your email for a secure PourGrid sign-in link.'};const value=String(error.message||error);if(/rate/i.test(value))return {ok:false,message:'Too many attempts. Wait a moment and try again.'};if(/network|fetch|offline/i.test(value))return {ok:false,message:'You appear to be offline. Reconnect and try again.'};return {ok:false,message:'The sign-in link could not be sent. Check your connection and retry.'}}
export function capabilities(role){return {view:ROLES.includes(role),mutate:['administrator','manager','inventory_staff'].includes(role),approve:['administrator','manager'].includes(role),baseline:['administrator','manager'].includes(role),reconcile:['administrator','manager'].includes(role),admin:role==='administrator'}}
export function authorizeContext(input,preferredLocation){const memberships=Array.isArray(input?.memberships)?input.memberships:[],organizations=Array.isArray(input?.organizations)?input.organizations:[],locations=Array.isArray(input?.locations)?input.locations:[],links=Array.isArray(input?.locationMemberships)?input.locationMemberships:[];const orgById=new Map(organizations.map(x=>[x.id,x])),locationById=new Map(locations.map(x=>[x.id,x]));const contexts=[];for(const membership of memberships){if(!membership||!membership.id||!membership.organization_id||!ROLES.includes(membership.role))continue;const org=orgById.get(membership.organization_id);if(!org)continue;for(const link of links.filter(x=>x.membership_id===membership.id)){const location=locationById.get(link.location_id);if(location&&location.organization_id===membership.organization_id)contexts.push({organizationId:org.id,organizationName:org.name,locationId:location.id,locationName:location.name,role:membership.role,capabilities:capabilities(membership.role)})}}if(!contexts.length)return {state:AUTH_STATES.PENDING,contexts:[]};const selected=contexts.find(x=>x.locationId===preferredLocation)||(contexts.length===1?contexts[0]:null);return {state:selected?AUTH_STATES.AUTHORIZED:AUTH_STATES.LOADING_CONTEXT,contexts,selected}}
export async function loadAuthorization(adapter,userId,preferredLocation){const memberships=await adapter.memberships(userId);if(!memberships.length)return {state:AUTH_STATES.PENDING,contexts:[]};const orgIds=[...new Set(memberships.map(x=>x.organization_id))],membershipIds=memberships.map(x=>x.id);const [organizations,locationMemberships]=await Promise.all([adapter.organizations(orgIds),adapter.locationMemberships(membershipIds)]);const locationIds=[...new Set(locationMemberships.map(x=>x.location_id))],locations=locationIds.length?await adapter.locations(locationIds):[];return authorizeContext({memberships,organizations,locationMemberships,locations},preferredLocation)}
export function clearSessionState(storage){const prefixes=['pourgrid-','sbb-','pg-'];for(let i=storage.length-1;i>=0;i--){const key=storage.key(i);if(key&&prefixes.some(prefix=>key.startsWith(prefix)))storage.removeItem(key)}}
