(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PourGridPhase3=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  var ROLES=['administrator','manager','inventory_staff','read_only_viewer'];
  var MUTATING=['administrator','manager','inventory_staff'];
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function id(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);}
  function assert(ok,message){if(!ok)throw new Error(message);}
  function can(role,action){
    if(ROLES.indexOf(role)<0)return false;
    if(action==='view')return true;
    if(action==='admin')return role==='administrator';
    if(action==='approve'||action==='finalize_baseline'||action==='reconcile')return role==='administrator'||role==='manager';
    return MUTATING.indexOf(role)>=0;
  }
  function locationLabel(context){if(!context||typeof context!=='object')return null;var organization=String(context.organizationName||'').trim(),location=String(context.locationName||'').trim();return organization&&location?organization+' · '+location:null;}
  function units(packages,loose,unitsPerPackage){
    var p=Number(packages||0),l=Number(loose||0),u=Number(unitsPerPackage||1);
    assert(Number.isInteger(p)&&p>=0&&Number.isInteger(l)&&l>=0&&Number.isInteger(u)&&u>0,'Quantities must be non-negative whole units');
    return p*u+l;
  }
  function remaining(line){return Math.max(0,Number(line.expectedUnits||0)-Number(line.receivedUnits||0));}
  function createState(){return {baseline:{status:'not_established',version:0},orders:[],sessions:[],balances:{},movements:[],audit:[],exceptions:[],reconciliations:[]};}
  function audit(state,event,actor,detail){state.audit.push(Object.freeze({id:id('audit'),at:new Date().toISOString(),event:event,actor:actor,detail:clone(detail||{})}));}
  function startSession(state,order,actor,role){assert(can(role,'mutate'),'Not authorized to receive');assert(order.status==='submitted'||order.status==='partially_received','Order is not receivable');var open=state.sessions.find(function(x){return x.orderId===order.id&&x.status==='in_progress';});if(open)return open;var session={id:id('receipt'),orderId:order.id,organizationId:order.organizationId,locationId:order.locationId,workflow:order.workflow,status:'in_progress',actor:actor,lines:order.lines.map(function(line){return {orderLineId:line.id,itemId:line.itemId,expectedUnits:line.expectedUnits,previouslyReceivedUnits:line.receivedUnits||0,receivedUnits:0,substitutionItemId:null,exceptionId:null};})};state.sessions.push(session);audit(state,'receiving.started',actor,{sessionId:session.id,orderId:order.id});return session;}
  function recordLine(state,session,lineId,input,actor,role){assert(can(role,'mutate'),'Not authorized to receive');assert(session.status==='in_progress','Receiving session is closed');var line=session.lines.find(function(x){return x.orderLineId===lineId;});assert(line,'Unknown receiving line');var amount=units(input.packages,input.loose,input.unitsPerPackage);var total=line.previouslyReceivedUnits+amount,sub=Boolean(input.substitutionItemId),over=total>line.expectedUnits;
    if(sub||over){var exception={id:id('exception'),sessionId:session.id,lineId:lineId,type:sub?'substitution':'over_receipt',status:'pending',requestedBy:actor,reason:String(input.reason||'').trim()};assert(exception.reason,'Exception reason is required');state.exceptions.push(exception);line.exceptionId=exception.id;}
    line.receivedUnits=amount;line.substitutionItemId=input.substitutionItemId||null;audit(state,'receiving.line_recorded',actor,{sessionId:session.id,lineId:lineId,units:amount,exceptionId:line.exceptionId});return line;
  }
  function decideException(state,exceptionId,approved,actor,role){assert(can(role,'approve'),'Manager approval required');var ex=state.exceptions.find(function(x){return x.id===exceptionId;});assert(ex&&ex.status==='pending','Exception is not pending');ex.status=approved?'approved':'rejected';ex.decidedBy=actor;ex.decidedAt=new Date().toISOString();audit(state,'exception.'+ex.status,actor,{exceptionId:ex.id});return ex;}
  function finalizeReceipt(state,sessionId,order,actor,role){assert(can(role,'mutate'),'Not authorized to finalize');var session=state.sessions.find(function(x){return x.id===sessionId;});assert(session,'Unknown receiving session');if(session.status==='finalized')return {session:session,movements:state.movements.filter(function(x){return x.sourceId===session.id;})};assert(state.baseline.status==='finalized','Inventory baseline is not finalized');assert(session.status==='in_progress','Receiving session is not open');assert(session.workflow===order.workflow,'Workflow mismatch');session.lines.forEach(function(line){if(line.exceptionId){var ex=state.exceptions.find(function(x){return x.id===line.exceptionId;});assert(ex&&ex.status==='approved','All exceptions require approval');}});
    var created=[];session.lines.forEach(function(line){if(!line.receivedUnits)return;var item=line.substitutionItemId||line.itemId,key=session.locationId+'|'+item,m={id:id('movement'),organizationId:session.organizationId,locationId:session.locationId,itemId:item,workflow:session.workflow,quantityUnits:line.receivedUnits,kind:'receipt',sourceId:session.id,createdAt:new Date().toISOString()};state.movements.push(Object.freeze(m));state.balances[key]=Number(state.balances[key]||0)+line.receivedUnits;created.push(m);var ol=order.lines.find(function(x){return x.id===line.orderLineId;});ol.receivedUnits=Number(ol.receivedUnits||0)+line.receivedUnits;});session.status='finalized';session.finalizedAt=new Date().toISOString();order.status=order.lines.every(function(x){return remaining(x)===0;})?'received':'partially_received';audit(state,'receiving.finalized',actor,{sessionId:session.id,movementIds:created.map(function(x){return x.id;})});return {session:session,movements:created};
  }
  function finalizeBaseline(state,counts,actor,role,scope){assert(can(role,'finalize_baseline'),'Manager approval required');assert(state.baseline.status!=='finalized','Use reconciliation to correct a finalized baseline');Object.keys(counts).forEach(function(item){var qty=Number(counts[item]);assert(Number.isInteger(qty)&&qty>=0,'Baseline counts must be whole units');var key=scope.locationId+'|'+item,m=Object.freeze({id:id('movement'),organizationId:scope.organizationId,locationId:scope.locationId,itemId:item,workflow:scope.workflowByItem&&scope.workflowByItem[item]||'bar',quantityUnits:qty,kind:'baseline',sourceId:'baseline-'+(state.baseline.version+1),createdAt:new Date().toISOString()});state.movements.push(m);state.balances[key]=qty;});state.baseline={status:'finalized',version:state.baseline.version+1,finalizedAt:new Date().toISOString(),finalizedBy:actor};audit(state,'baseline.finalized',actor,{version:state.baseline.version});return state.baseline;}
  function reconstruct(state,locationId,itemId){return state.movements.filter(function(x){return x.locationId===locationId&&x.itemId===itemId;}).reduce(function(sum,x){return sum+x.quantityUnits;},0);}
  function requestReconciliation(state,scope,itemId,quantityUnits,reason,actor,role){assert(can(role,'mutate'),'Not authorized');assert(Number.isInteger(quantityUnits)&&quantityUnits!==0,'A non-zero whole-unit adjustment is required');var req={id:id('recon'),organizationId:scope.organizationId,locationId:scope.locationId,itemId:itemId,workflow:scope.workflow,quantityUnits:quantityUnits,reason:reason,status:'pending',requestedBy:actor};state.reconciliations.push(req);audit(state,'reconciliation.requested',actor,{requestId:req.id});return req;}
  function approveReconciliation(state,requestId,approved,actor,role){assert(can(role,'reconcile'),'Manager approval required');var req=state.reconciliations.find(function(x){return x.id===requestId;});assert(req&&req.status==='pending','Reconciliation is not pending');req.status=approved?'approved':'rejected';req.decidedBy=actor;if(approved){var m=Object.freeze({id:id('movement'),organizationId:req.organizationId,locationId:req.locationId,itemId:req.itemId,workflow:req.workflow,quantityUnits:req.quantityUnits,kind:'reconciliation',sourceId:req.id,createdAt:new Date().toISOString()}),key=req.locationId+'|'+req.itemId;state.movements.push(m);state.balances[key]=Number(state.balances[key]||0)+req.quantityUnits;}audit(state,'reconciliation.'+req.status,actor,{requestId:req.id});return req;}
  return {ROLES:ROLES,can:can,locationLabel:locationLabel,units:units,remaining:remaining,createState:createState,startSession:startSession,recordLine:recordLine,decideException:decideException,finalizeReceipt:finalizeReceipt,finalizeBaseline:finalizeBaseline,reconstruct:reconstruct,requestReconciliation:requestReconciliation,approveReconciliation:approveReconciliation};
});
