(function(){
"use strict";
var BACKUP="pourgrid-local-draft-backup-v1",QUEUE="pourgrid-shared-draft-queue-v1",SESSION="pourgrid-shared-session-v1";
var states={},sessionId=sessionStorage.getItem(SESSION)||crypto.randomUUID();sessionStorage.setItem(SESSION,sessionId);
// Local draft state belongs to the active property, never the device.
function store(){return window.PG_STORE||localStorage}
function read(key,fallback){try{return JSON.parse(store().getItem(key))??fallback}catch(_){return fallback}}
function write(key,value){store().setItem(key,JSON.stringify(value))}
function backupOnce(){if(store().getItem(BACKUP))return;var keys=["sbb-counts","pourgrid-drafts-v1","sbb-notes","sbb-adjustments","sbb-adjustment-meta","pourgrid-session"];
 var data={version:1,createdAt:new Date().toISOString(),values:{}};keys.forEach(function(k){if(store().getItem(k)!==null)data.values[k]=store().getItem(k)});write(BACKUP,data)}
function downloadBackup(){backupOnce();var a=document.createElement("a"),blob=new Blob([store().getItem(BACKUP)],{type:"application/json"});a.href=URL.createObjectURL(blob);a.download="pourgrid-local-draft-backup.json";a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},0)}
// Marks the failures that happen before anything is sent to the database, so the order
// save can safely re-route to the direct location-scoped RPC instead of losing the order.
function neverSent(text){var error=new Error(text);error.pgNeverSent=true;return error}
function api(){if(!window.POURGRID_SHARED_DRAFT_API)throw neverSent("Shared draft service unavailable");return window.POURGRID_SHARED_DRAFT_API}
function notify(type){window.dispatchEvent(new CustomEvent("pourgrid:shared-draft",{detail:status(type)}))}
function set(type,patch){states[type]=Object.assign(states[type]||{type:type,status:"connecting",fields:{},queue:[],conflicts:[]},patch);notify(type);return states[type]}
function status(type){var s=states[type]||{};return {type:type,status:s.status||"connecting",lastSync:s.lastSync||null,updatedBy:s.updatedBy||null,presence:s.presence||[],conflicts:s.conflicts||[],revision:s.revision||0,realtimeState:s.channel&&s.channel.state||"closed"}}
function keyOf(product,field){return product+"\u001f"+field}
function productNames(type){var products=type==="merchants"?window.MER:window.BAR;return new Set(Array.isArray(products)?products.map(function(product){return product&&product.name}).filter(Boolean):[])}
function owns(type,product){if(product==="$workflow")return true;var names=productNames(type);return !names.size||names.has(product)}
function scalar(value){if(value===null||value===undefined)return null;if(typeof value==="number")return isFinite(value)?value:null;if(typeof value==="string"&&value.trim()!==""&&!isNaN(Number(value)))return Number(value);return value}
function sameValue(field,a,b){if(JSON.stringify(a)===JSON.stringify(b))return true;return ["count","cases","halves","loose","adjustment"].indexOf(field)>=0&&scalar(a)!==null&&scalar(a)===scalar(b)}
function visibleConflicts(conflicts){var byField={};(conflicts||[]).forEach(function(conflict){if(sameValue(conflict.fieldKey,conflict.serverValue,conflict.incomingValue))return;byField[keyOf(conflict.productKey,conflict.fieldKey)]=conflict});return Object.keys(byField).map(function(key){return byField[key]})}
function localFields(type){var counts=read("sbb-counts",{}),fields=[];Object.keys(counts).forEach(function(k){var p=k,f="count",i=k.lastIndexOf("::");if(i>0){p=k.slice(0,i);f=k.slice(i+2)}if(owns(type,p)&&["count","cases","halves","loose"].indexOf(f)>=0)fields.push({productKey:p,fieldKey:f,value:counts[k]})});
 var notes=read("sbb-notes",{}),adjs=read("sbb-adjustments",{}),meta=read("sbb-adjustment-meta",{});if(notes[type])fields.push({productKey:"$workflow",fieldKey:"note",value:notes[type]});Object.keys(adjs).forEach(function(k){if(owns(type,k))fields.push({productKey:k,fieldKey:"adjustment",value:adjs[k]})});Object.keys(meta).forEach(function(k){if(owns(type,k))fields.push({productKey:k,fieldKey:"adjustment_meta",value:meta[k]})});return fields}
function apply(snapshot,type){if(!snapshot)return;var counts=read("sbb-counts",{}),notes=read("sbb-notes",{}),adjs=read("sbb-adjustments",{}),meta=read("sbb-adjustment-meta",{}),pending=((states[type]||{}).queue||[]);
 function applyField(f){if(!owns(type,f.productKey))return;var k=f.fieldKey==="count"?f.productKey:f.productKey+"::"+f.fieldKey;if(["count","cases","halves","loose"].indexOf(f.fieldKey)>=0)counts[k]=f.value;else if(f.productKey==="$workflow"&&f.fieldKey==="note")notes[snapshot.workspace]=f.value;else if(f.fieldKey==="adjustment"){if(!Number(f.value))delete adjs[f.productKey];else adjs[f.productKey]=f.value}else if(f.fieldKey==="adjustment_meta"){if(!f.value||typeof f.value==="object"&&!Object.keys(f.value).length)delete meta[f.productKey];else meta[f.productKey]=f.value}}
 (snapshot.fields||[]).forEach(applyField);pending.forEach(function(item){applyField({productKey:item.product,fieldKey:item.field,value:item.value})});write("sbb-counts",counts);write("sbb-notes",notes);write("sbb-adjustments",adjs);write("sbb-adjustment-meta",meta);if(window.S){S.counts=counts;S.notes=notes;S.adjustments=adjs;S.adjustmentMeta=meta}}
async function refresh(type){var snap=await api().read(type);if(!snap)return null;var map={},conflicts=visibleConflicts(snap.conflicts);(snap.fields||[]).forEach(function(f){if(owns(type,f.productKey))map[keyOf(f.productKey,f.fieldKey)]=f});apply(snap,type);set(type,{id:snap.id,revision:snap.revision,reviewedRevision:snap.reviewedRevision,fields:map,conflicts:conflicts,lastSync:new Date().toISOString(),updatedBy:snap.updatedBy,status:conflicts.length?"conflict":"synced"});return snap}
async function flush(type){var s=states[type];if(!s||s.flushing||!s.queue.length)return;s.flushing=true;set(type,{status:navigator.onLine?"syncing":"offline-saved"});try{while(s.queue.length){var m=s.queue[0],sentKey=m.key,r=await api().update(s.id,m.product,m.field,m.value,m.expected,sentKey);if(r.status==="conflict"){if(s.queue[0]&&s.queue[0].key===sentKey)s.queue.shift();if(!(s.conflicts||[]).some(function(x){return r.conflictId&&x.id===r.conflictId}))s.conflicts.push(Object.assign({},m,r,{id:r.conflictId||null,productKey:m.product,fieldKey:m.field}));write(QUEUE,Object.values(states).flatMap(function(x){return x.queue||[]}));set(type,{status:"conflict"});continue}if(s.queue[0]&&s.queue[0].key===sentKey)s.queue.shift();write(QUEUE,Object.values(states).flatMap(function(x){return x.queue||[]}));await refresh(type)}if(!s.queue.length)set(type,{status:s.conflicts.length?"conflict":"synced",lastSync:new Date().toISOString()})}catch(e){set(type,{status:navigator.onLine?"unsynced":"offline-saved",error:String(e.message||e)})}finally{s.flushing=false}}
function queue(type,product,field,value){var s=states[type];if(!s||!s.id)return;var current=s.fields[keyOf(product,field)],existing=(s.queue||[]).find(function(item){return item.draft===s.id&&item.product===product&&item.field===field}),key=crypto.randomUUID();if(existing){existing.value=value;existing.key=key}else s.queue.push({type:type,draft:s.id,product:product,field:field,value:value,expected:current?current.revision:null,key:key});write(QUEUE,Object.values(states).flatMap(function(x){return x.queue||[]}));set(type,{status:navigator.onLine?"unsynced":"offline-saved"});flush(type)}
function syncCounts(counts){["bar","merchants"].forEach(function(type){var s=states[type];if(!s||!s.id)return;Object.keys(counts||{}).forEach(function(k){var p=k,f="count",i=k.lastIndexOf("::");if(i>0){p=k.slice(0,i);f=k.slice(i+2)}if(!owns(type,p)||["count","cases","halves","loose"].indexOf(f)<0)return;var old=s.fields[keyOf(p,f)];if(!old||!sameValue(f,old.value,counts[k]))queue(type,p,f,counts[k])})})}
function clearAdjustment(type,product){queue(type,product,"adjustment",0);queue(type,product,"adjustment_meta",{})}
async function open(type){backupOnce();set(type,{status:"connecting",queue:read(QUEUE,[]).filter(function(x){return x.type===type})});var seasonal=window.pgSession?((pgSession()[type]||{}).seasonalProfile):null,id=await api().open(type,seasonal),snap=await api().read(type);if(!snap)throw new Error("Shared draft did not open");set(type,{id:id});if(!(snap.fields||[]).length){var local=localFields(type),legacy=window.pgSession?((pgSession()[type]||{}).id||""):"";if(local.length)await api().importLegacy(type,legacy,local,seasonal,crypto.randomUUID())}await refresh(type);var s=states[type];if(s.channel&&s.channel.unsubscribe)s.channel.unsubscribe();s.channel=api().subscribe(s.id,function(){refresh(type)});setInterval(function(){api().heartbeat(s.id,sessionId).then(function(){return api().presence(s.id)}).then(function(p){set(type,{presence:p||[]})}).catch(function(){})},30000);api().heartbeat(s.id,sessionId).catch(function(){});flush(type);return states[type]}
async function review(type){await flush(type);var s=states[type];if(!s)throw neverSent("Shared draft state is unavailable");if(s.queue.length||s.conflicts.length)throw neverSent("Resolve shared draft changes before Review");var snap=await api().review(s.id);set(type,{reviewedRevision:snap.revision,status:"synced"});return snap}
async function resolveConflict(type,conflictId,resolution,productKey,fieldKey){
 var s=states[type],conflict=s&&(s.conflicts||[]).find(function(x){return conflictId?x.id===conflictId:x.productKey===productKey&&x.fieldKey===fieldKey});
 if(!s||!conflict||["server","incoming"].indexOf(resolution)<0)throw neverSent("A valid shared draft conflict choice is required");
 await api().resolve(conflictId,resolution,s.id,conflict.productKey,conflict.fieldKey);
 s.queue=(s.queue||[]).filter(function(item){return item.product!==conflict.productKey||item.field!==conflict.fieldKey});
 write(QUEUE,Object.values(states).flatMap(function(x){return x.queue||[]}));
 await refresh(type);return status(type);
}
// Nothing before api().finalize can write an order row, so every failure up to that point
// is flagged as never-sent and the caller may fall back to the direct order save. From the
// finalize call onward the outcome is unknown, and the error is left alone on purpose.
async function finalize(type,order){var s;
 try{await flush(type);s=states[type];if(!s||!s.id||s.queue.length||s.conflicts.length)throw neverSent("Shared draft is not fully synced");if(s.reviewedRevision!==s.revision)await review(type)}
 catch(e){if(e&&typeof e==="object")e.pgNeverSent=true;set(type,{status:"save-failed"});throw e}
 order=Object.assign({},order,{draftId:s.id});set(type,{status:"saving"});try{var id=await api().finalize(s.id,s.revision,order);set(type,{status:"synced",closed:true});return id}catch(e){set(type,{status:"save-failed"});throw e}}
async function init(){backupOnce();await Promise.all([open("bar"),open("merchants")]);window.addEventListener("online",function(){Object.keys(states).forEach(flush)});return states}
window.PourGridSharedDraft=Object.freeze({init:init,refresh:refresh,syncCounts:syncCounts,queue:queue,clearAdjustment:clearAdjustment,review:review,resolveConflict:resolveConflict,finalize:finalize,status:status,backupOnce:backupOnce,downloadBackup:downloadBackup});
})();
