-- Phase 3 forward-only foundation. Safe for confirmed public.orders(id, created_at, data).
begin;
do $$ begin
  if to_regclass('public.orders') is null then raise exception 'Preflight: public.orders is missing'; end if;
  if not exists(select 1 from information_schema.columns where table_schema='public' and table_name='orders' and column_name='data' and data_type='jsonb') then raise exception 'Preflight: public.orders.data jsonb is missing'; end if;
end $$;

create extension if not exists pgcrypto;
create type public.app_role as enum ('administrator','manager','inventory_staff','read_only_viewer');
create type public.workflow_kind as enum ('bar','merchants');
create type public.order_status as enum ('draft','submitted','partially_received','received','cancelled');
create type public.session_status as enum ('in_progress','finalized','cancelled');
create type public.approval_status as enum ('pending','approved','rejected');
create type public.baseline_status as enum ('in_progress','finalized');
create type public.movement_kind as enum ('baseline','receipt','reconciliation','correction');

create table public.organizations(id uuid primary key default gen_random_uuid(), name text not null unique, created_at timestamptz not null default now());
create table public.locations(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, name text not null, created_at timestamptz not null default now(), unique(organization_id,name));
create table public.profiles(id uuid primary key references auth.users on delete cascade, display_name text, created_at timestamptz not null default now());
create table public.memberships(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, user_id uuid not null references public.profiles, role public.app_role not null, created_at timestamptz not null default now(), unique(organization_id,user_id));
create table public.location_memberships(membership_id uuid not null references public.memberships on delete cascade, location_id uuid not null references public.locations on delete cascade, primary key(membership_id,location_id));
create table public.vendors(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, name text not null, workflow public.workflow_kind not null, active boolean not null default true, unique(organization_id,name));
create table public.inventory_items(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, sku text, name text not null, workflow public.workflow_kind not null, units_per_package integer not null check(units_per_package>0), active boolean not null default true, unique(organization_id,name));
create table public.structured_orders(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, vendor_id uuid not null references public.vendors, workflow public.workflow_kind not null, status public.order_status not null default 'draft', submitted_at timestamptz, created_by uuid not null references public.profiles, created_at timestamptz not null default now());
create table public.order_lines(id uuid primary key default gen_random_uuid(), order_id uuid not null references public.structured_orders, item_id uuid not null references public.inventory_items, draft_units integer not null default 0 check(draft_units>=0), submitted_units integer check(submitted_units>=0), expected_units integer check(expected_units>=0), received_units integer not null default 0 check(received_units>=0), units_per_package integer not null check(units_per_package>0), unique(order_id,item_id));
create table public.receiving_sessions(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, order_id uuid not null references public.structured_orders, workflow public.workflow_kind not null, status public.session_status not null default 'in_progress', idempotency_key uuid not null default gen_random_uuid() unique, notes text, evidence jsonb not null default '[]', created_by uuid not null references public.profiles, created_at timestamptz not null default now(), finalized_at timestamptz);
create table public.receiving_lines(id uuid primary key default gen_random_uuid(), session_id uuid not null references public.receiving_sessions, order_line_id uuid not null references public.order_lines, received_packages integer not null default 0 check(received_packages>=0), received_loose_units integer not null default 0 check(received_loose_units>=0), received_units integer not null check(received_units>=0), substitution_item_id uuid references public.inventory_items, notes text, unique(session_id,order_line_id));
create table public.approved_exceptions(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, receiving_line_id uuid not null references public.receiving_lines, exception_type text not null check(exception_type in ('substitution','over_receipt')), status public.approval_status not null default 'pending', reason text not null check(length(trim(reason))>0), requested_by uuid not null references public.profiles, decided_by uuid references public.profiles, decided_at timestamptz, created_at timestamptz not null default now());
create table public.inventory_baselines(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, status public.baseline_status not null default 'in_progress', version integer not null check(version>0), created_by uuid not null references public.profiles, finalized_by uuid references public.profiles, created_at timestamptz not null default now(), finalized_at timestamptz, unique(location_id,version));
create table public.inventory_baseline_lines(id uuid primary key default gen_random_uuid(), baseline_id uuid not null references public.inventory_baselines, item_id uuid not null references public.inventory_items, counted_units integer not null check(counted_units>=0), unique(baseline_id,item_id));
create table public.location_inventory_balances(organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, item_id uuid not null references public.inventory_items, quantity_units bigint not null default 0, updated_at timestamptz not null default now(), primary key(location_id,item_id));
create table public.inventory_movements(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, item_id uuid not null references public.inventory_items, workflow public.workflow_kind not null, kind public.movement_kind not null, quantity_units integer not null check(quantity_units<>0), source_table text not null, source_id uuid not null, reverses_movement_id uuid references public.inventory_movements, created_by uuid not null references public.profiles, created_at timestamptz not null default now(), unique(source_table,source_id,item_id));
create table public.reconciliation_requests(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid not null references public.locations, item_id uuid not null references public.inventory_items, workflow public.workflow_kind not null, requested_adjustment_units integer not null check(requested_adjustment_units<>0), reason text not null check(length(trim(reason))>0), status public.approval_status not null default 'pending', requested_by uuid not null references public.profiles, decided_by uuid references public.profiles, decided_at timestamptz, created_at timestamptz not null default now());
create table public.audit_events(id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations, location_id uuid references public.locations, actor_id uuid references public.profiles, event_type text not null, entity_table text not null, entity_id uuid, detail jsonb not null default '{}', occurred_at timestamptz not null default now());
create table public.legacy_order_references(legacy_order_id bigint primary key references public.orders(id), classification text not null default 'legacy_unassigned' check(classification='legacy_unassigned'), organization_id uuid references public.organizations, assigned_by uuid references public.profiles, assigned_at timestamptz, check((organization_id is null)=(assigned_at is null)));
insert into public.legacy_order_references(legacy_order_id) select id from public.orders on conflict do nothing;

create function public.has_location_role(p_org uuid,p_location uuid,p_roles public.app_role[]) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from memberships m join location_memberships lm on lm.membership_id=m.id where m.organization_id=p_org and m.user_id=auth.uid() and lm.location_id=p_location and m.role=any(p_roles))$$;
revoke all on function public.has_location_role(uuid,uuid,public.app_role[]) from public; grant execute on function public.has_location_role(uuid,uuid,public.app_role[]) to authenticated;

create function public.block_immutable_change() returns trigger language plpgsql set search_path=public,pg_temp as $$begin raise exception '% is immutable',tg_table_name; end$$;
create trigger immutable_movements before update or delete on public.inventory_movements for each row execute function public.block_immutable_change();
create trigger immutable_audit before update or delete on public.audit_events for each row execute function public.block_immutable_change();

create function public.apply_movement_balance() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$begin insert into location_inventory_balances(organization_id,location_id,item_id,quantity_units) values(new.organization_id,new.location_id,new.item_id,new.quantity_units) on conflict(location_id,item_id) do update set quantity_units=location_inventory_balances.quantity_units+excluded.quantity_units,updated_at=now(); return new; end$$;
create trigger movement_updates_balance after insert on public.inventory_movements for each row execute function public.apply_movement_balance();

do $$declare t text; begin foreach t in array array['organizations','locations','profiles','memberships','location_memberships','vendors','inventory_items','structured_orders','order_lines','receiving_sessions','receiving_lines','approved_exceptions','inventory_baselines','inventory_baseline_lines','location_inventory_balances','inventory_movements','reconciliation_requests','audit_events','legacy_order_references'] loop execute format('alter table public.%I enable row level security',t); execute format('revoke all on public.%I from anon, authenticated',t); execute format('grant select on public.%I to authenticated',t); end loop; end$$;
revoke all on public.orders from anon,authenticated;

-- Read access is membership/location scoped. Writes use narrow RPCs added in the next migration.
create policy org_read on public.organizations for select to authenticated using(exists(select 1 from public.memberships m where m.organization_id=id and m.user_id=auth.uid()));
create policy location_read on public.locations for select to authenticated using(public.has_location_role(organization_id,id,array['administrator','manager','inventory_staff','read_only_viewer']::public.app_role[]));
do $$declare t text; begin foreach t in array array['vendors','inventory_items'] loop execute format('create policy tenant_read on public.%I for select to authenticated using (exists(select 1 from public.memberships m where m.organization_id=%I.organization_id and m.user_id=auth.uid()))',t,t); end loop; end$$;
do $$declare t text; begin foreach t in array array['structured_orders','receiving_sessions','approved_exceptions','inventory_baselines','location_inventory_balances','inventory_movements','reconciliation_requests','audit_events'] loop execute format('create policy tenant_read on public.%I for select to authenticated using (public.has_location_role(organization_id,location_id,array[''administrator'',''manager'',''inventory_staff'',''read_only_viewer'']::public.app_role[]))',t); end loop; end$$;
create policy profile_self on public.profiles for select to authenticated using(id=auth.uid());
create policy membership_self on public.memberships for select to authenticated using(user_id=auth.uid());
create policy location_membership_self on public.location_memberships for select to authenticated using(exists(select 1 from public.memberships m where m.id=membership_id and m.user_id=auth.uid()));
create policy order_line_read on public.order_lines for select to authenticated using(exists(select 1 from public.structured_orders o where o.id=order_id and public.has_location_role(o.organization_id,o.location_id,array['administrator','manager','inventory_staff','read_only_viewer']::public.app_role[])));
create policy receiving_line_read on public.receiving_lines for select to authenticated using(exists(select 1 from public.receiving_sessions s where s.id=session_id and public.has_location_role(s.organization_id,s.location_id,array['administrator','manager','inventory_staff','read_only_viewer']::public.app_role[])));
create policy baseline_line_read on public.inventory_baseline_lines for select to authenticated using(exists(select 1 from public.inventory_baselines b where b.id=baseline_id and public.has_location_role(b.organization_id,b.location_id,array['administrator','manager','inventory_staff','read_only_viewer']::public.app_role[])));
-- Legacy JSON stays quarantined: no client policy exists. Administrative assignment requires a later approved RPC.

commit;
