alter table public.profit_lab_recipes add column if not exists source_key text, add column if not exists source_file text, add column if not exists source_version text, add column if not exists source_imported_at timestamptz;
create unique index if not exists profit_lab_recipes_source_key_uq on public.profit_lab_recipes(organization_id,location_id,source_key) where source_key is not null;
create or replace function public.import_profit_lab_current_menu(p_organization uuid,p_location uuid,p_recipes jsonb,p_source_file text,p_source_version text)
returns table(imported integer,skipped integer,conflicts integer) language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$
declare item jsonb;saved public.profit_lab_recipes;added integer:=0;ignored integer:=0;collided integer:=0;recipe_name text;recipe_key text;
begin
 if auth.uid() is null or not public.has_location_role(p_organization,p_location,array['administrator','manager','bar_lead']::public.app_role[]) then raise exception 'Profit Lab editor access required'; end if;
 if p_source_file<>'Sapphire Beach Bar Order Guide v12.xlsx' or p_source_version<>'v12' or jsonb_typeof(p_recipes)<>'array' then raise exception 'Unsupported Current Menu source'; end if;
 for item in select value from jsonb_array_elements(p_recipes) loop
  recipe_name:=btrim(coalesce(item->>'name',''));recipe_key:=nullif(item->>'sourceKey','');if recipe_key is null or recipe_name='' then raise exception 'Every Current Menu recipe needs a source key and name';end if;perform public.profit_lab_validate_ingredients(item->'ingredients');
  if exists(select 1 from public.profit_lab_recipes r where r.organization_id=p_organization and r.location_id=p_location and r.source_key=recipe_key) then ignored:=ignored+1;continue;end if;
  if exists(select 1 from public.profit_lab_recipes r where r.organization_id=p_organization and r.location_id=p_location and lower(r.name)=lower(recipe_name)) then collided:=collided+1;continue;end if;
  insert into public.profit_lab_recipes(organization_id,location_id,name,target_cost_percent,menu_price,ingredients,status,outlet,preparation,notes,target_volume_oz,created_by,updated_by,source_key,source_file,source_version,source_imported_at) values(p_organization,p_location,recipe_name,coalesce((item->>'target')::numeric,18),(item->>'menuPrice')::numeric,item->'ingredients','Approved','Current Menu','',coalesce(item->>'notes',''),coalesce((item->>'targetVolumeOz')::numeric,6),auth.uid(),auth.uid(),recipe_key,p_source_file,p_source_version,now()) returning * into saved;
  insert into public.profit_lab_recipe_revisions(recipe_id,organization_id,location_id,version,snapshot,action,changed_by) values(saved.id,p_organization,p_location,saved.version,to_jsonb(saved),'current_menu_import',auth.uid());added:=added+1;
 end loop;return query select added,ignored,collided;
end$$;
revoke all on function public.import_profit_lab_current_menu(uuid,uuid,jsonb,text,text) from public,anon;grant execute on function public.import_profit_lab_current_menu(uuid,uuid,jsonb,text,text) to authenticated;
drop function public.list_profit_lab_recipes(uuid,uuid);
create function public.list_profit_lab_recipes(p_organization uuid,p_location uuid) returns table(id uuid,name text,target_cost_percent numeric,menu_price numeric,ingredients jsonb,version integer,created_by uuid,updated_by uuid,created_at timestamptz,updated_at timestamptz,can_delete boolean,status text,outlet text,preparation text,notes text,target_volume_oz numeric,archived_at timestamptz,source_key text,source_file text,source_version text,source_imported_at timestamptz) language plpgsql security definer stable set search_path=pg_catalog,public,pg_temp as $$begin if auth.uid() is null or not public.has_location_role(p_organization,p_location,array['administrator','manager','bar_lead','inventory_staff','read_only_viewer']::public.app_role[]) then raise exception 'Profit Lab access required';end if;return query select r.id,r.name,r.target_cost_percent,r.menu_price,r.ingredients,r.version,r.created_by,r.updated_by,r.created_at,r.updated_at,public.has_location_role(p_organization,p_location,array['administrator','manager']::public.app_role[]),r.status,r.outlet,r.preparation,r.notes,r.target_volume_oz,r.archived_at,r.source_key,r.source_file,r.source_version,r.source_imported_at from public.profit_lab_recipes r where r.organization_id=p_organization and r.location_id=p_location order by (r.archived_at is not null),lower(r.name);end$$;
revoke all on function public.list_profit_lab_recipes(uuid,uuid) from public,anon;grant execute on function public.list_profit_lab_recipes(uuid,uuid) to authenticated;
